// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module face_detect_face_detect_Pipeline_VITIS_LOOP_2810_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        result_x_address0,
        result_x_ce0,
        result_x_we0,
        result_x_d0,
        result_y_address0,
        result_y_ce0,
        result_y_we0,
        result_y_d0,
        result_w_address0,
        result_w_ce0,
        result_w_we0,
        result_w_d0,
        result_h_address0,
        result_h_ce0,
        result_h_we0,
        result_h_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] result_x_address0;
output   result_x_ce0;
output   result_x_we0;
output  [31:0] result_x_d0;
output  [6:0] result_y_address0;
output   result_y_ce0;
output   result_y_we0;
output  [31:0] result_y_d0;
output  [6:0] result_w_address0;
output   result_w_ce0;
output   result_w_we0;
output  [31:0] result_w_d0;
output  [6:0] result_h_address0;
output   result_h_ce0;
output   result_h_we0;
output  [31:0] result_h_d0;

reg ap_idle;
reg result_x_ce0;
reg result_x_we0;
reg result_y_ce0;
reg result_y_we0;
reg result_w_ce0;
reg result_w_we0;
reg result_h_ce0;
reg result_h_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln2810_fu_108_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] i_cast_fu_120_p1;
reg   [6:0] i_fu_40;
wire   [6:0] add_ln2810_fu_114_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

face_detect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln2810_fu_108_p2 == 1'd0)) begin
            i_fu_40 <= add_ln2810_fu_114_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_40 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2810_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_40;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_h_ce0 = 1'b1;
    end else begin
        result_h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2810_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_h_we0 = 1'b1;
    end else begin
        result_h_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_w_ce0 = 1'b1;
    end else begin
        result_w_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2810_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_w_we0 = 1'b1;
    end else begin
        result_w_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_x_ce0 = 1'b1;
    end else begin
        result_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2810_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_x_we0 = 1'b1;
    end else begin
        result_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_y_ce0 = 1'b1;
    end else begin
        result_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2810_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        result_y_we0 = 1'b1;
    end else begin
        result_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2810_fu_114_p2 = (ap_sig_allocacmp_i_3 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_cast_fu_120_p1 = ap_sig_allocacmp_i_3;

assign icmp_ln2810_fu_108_p2 = ((ap_sig_allocacmp_i_3 == 7'd100) ? 1'b1 : 1'b0);

assign result_h_address0 = i_cast_fu_120_p1;

assign result_h_d0 = 32'd0;

assign result_w_address0 = i_cast_fu_120_p1;

assign result_w_d0 = 32'd0;

assign result_x_address0 = i_cast_fu_120_p1;

assign result_x_d0 = 32'd0;

assign result_y_address0 = i_cast_fu_120_p1;

assign result_y_d0 = 32'd0;

endmodule //face_detect_face_detect_Pipeline_VITIS_LOOP_2810_2
