// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="face_detect_face_detect,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.258625,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=90,HLS_SYN_DSP=0,HLS_SYN_FF=59732,HLS_SYN_LUT=74965,HLS_VERSION=2022_2}" *)

module face_detect (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inData_address0,
        inData_ce0,
        inData_q0,
        result_x_address0,
        result_x_ce0,
        result_x_we0,
        result_x_d0,
        result_y_address0,
        result_y_ce0,
        result_y_we0,
        result_y_d0,
        result_w_address0,
        result_w_ce0,
        result_w_we0,
        result_w_d0,
        result_h_address0,
        result_h_ce0,
        result_h_we0,
        result_h_d0,
        result_size,
        result_size_ap_vld
);

parameter    ap_ST_fsm_state1 = 46'd1;
parameter    ap_ST_fsm_state2 = 46'd2;
parameter    ap_ST_fsm_state3 = 46'd4;
parameter    ap_ST_fsm_state4 = 46'd8;
parameter    ap_ST_fsm_state5 = 46'd16;
parameter    ap_ST_fsm_state6 = 46'd32;
parameter    ap_ST_fsm_state7 = 46'd64;
parameter    ap_ST_fsm_state8 = 46'd128;
parameter    ap_ST_fsm_state9 = 46'd256;
parameter    ap_ST_fsm_state10 = 46'd512;
parameter    ap_ST_fsm_state11 = 46'd1024;
parameter    ap_ST_fsm_state12 = 46'd2048;
parameter    ap_ST_fsm_state13 = 46'd4096;
parameter    ap_ST_fsm_state14 = 46'd8192;
parameter    ap_ST_fsm_state15 = 46'd16384;
parameter    ap_ST_fsm_state16 = 46'd32768;
parameter    ap_ST_fsm_state17 = 46'd65536;
parameter    ap_ST_fsm_state18 = 46'd131072;
parameter    ap_ST_fsm_state19 = 46'd262144;
parameter    ap_ST_fsm_state20 = 46'd524288;
parameter    ap_ST_fsm_state21 = 46'd1048576;
parameter    ap_ST_fsm_state22 = 46'd2097152;
parameter    ap_ST_fsm_state23 = 46'd4194304;
parameter    ap_ST_fsm_state24 = 46'd8388608;
parameter    ap_ST_fsm_state25 = 46'd16777216;
parameter    ap_ST_fsm_state26 = 46'd33554432;
parameter    ap_ST_fsm_state27 = 46'd67108864;
parameter    ap_ST_fsm_state28 = 46'd134217728;
parameter    ap_ST_fsm_state29 = 46'd268435456;
parameter    ap_ST_fsm_state30 = 46'd536870912;
parameter    ap_ST_fsm_state31 = 46'd1073741824;
parameter    ap_ST_fsm_state32 = 46'd2147483648;
parameter    ap_ST_fsm_state33 = 46'd4294967296;
parameter    ap_ST_fsm_state34 = 46'd8589934592;
parameter    ap_ST_fsm_state35 = 46'd17179869184;
parameter    ap_ST_fsm_state36 = 46'd34359738368;
parameter    ap_ST_fsm_state37 = 46'd68719476736;
parameter    ap_ST_fsm_state38 = 46'd137438953472;
parameter    ap_ST_fsm_state39 = 46'd274877906944;
parameter    ap_ST_fsm_state40 = 46'd549755813888;
parameter    ap_ST_fsm_state41 = 46'd1099511627776;
parameter    ap_ST_fsm_state42 = 46'd2199023255552;
parameter    ap_ST_fsm_state43 = 46'd4398046511104;
parameter    ap_ST_fsm_state44 = 46'd8796093022208;
parameter    ap_ST_fsm_state45 = 46'd17592186044416;
parameter    ap_ST_fsm_state46 = 46'd35184372088832;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] inData_address0;
output   inData_ce0;
input  [7:0] inData_q0;
output  [6:0] result_x_address0;
output   result_x_ce0;
output   result_x_we0;
output  [31:0] result_x_d0;
output  [6:0] result_y_address0;
output   result_y_ce0;
output   result_y_we0;
output  [31:0] result_y_d0;
output  [6:0] result_w_address0;
output   result_w_ce0;
output   result_w_we0;
output  [31:0] result_w_d0;
output  [6:0] result_h_address0;
output   result_h_ce0;
output   result_h_we0;
output  [31:0] result_h_d0;
output  [31:0] result_size;
output   result_size_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] result_x_address0;
reg result_x_ce0;
reg result_x_we0;
reg[31:0] result_x_d0;
reg[6:0] result_y_address0;
reg result_y_ce0;
reg result_y_we0;
reg[31:0] result_y_d0;
reg[6:0] result_w_address0;
reg result_w_ce0;
reg result_w_we0;
reg[31:0] result_w_d0;
reg[6:0] result_h_address0;
reg result_h_ce0;
reg result_h_we0;
reg[31:0] result_h_d0;
reg result_size_ap_vld;

(* fsm_encoding = "none" *) reg   [45:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] counter;
reg   [16:0] Data_address0;
reg    Data_ce0;
reg    Data_we0;
wire   [7:0] Data_q0;
wire   [0:0] icmp_ln2804_fu_414_p2;
reg   [0:0] icmp_ln2804_reg_1086;
wire   [16:0] add_ln2806_fu_436_p2;
reg   [16:0] add_ln2806_reg_1090;
wire   [31:0] add_ln2808_fu_443_p2;
reg   [31:0] add_ln2808_reg_1095;
wire    ap_CS_fsm_state2;
reg   [31:0] factor_2_reg_1117;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_374_p2;
reg   [31:0] dc_2_reg_1123;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_379_p2;
reg   [31:0] dc_3_reg_1129;
wire   [0:0] grp_fu_387_p2;
reg   [0:0] tmp_s_reg_1135;
wire    ap_CS_fsm_state9;
wire   [0:0] tmp_13_fu_392_p2;
reg   [0:0] tmp_13_reg_1140;
reg   [31:0] res_size_Scale_1_load_reg_1145;
wire    ap_CS_fsm_state10;
wire   [22:0] p_Result_8_fu_525_p1;
reg   [22:0] p_Result_8_reg_1150;
reg   [0:0] p_Result_5_reg_1158;
wire   [0:0] and_ln2838_fu_552_p2;
wire   [31:0] val_2_fu_668_p3;
reg   [31:0] val_2_reg_1164;
reg   [0:0] p_Result_7_reg_1171;
reg   [7:0] xs_exp_V_3_reg_1177;
wire   [31:0] val_3_fu_789_p3;
reg   [31:0] val_3_reg_1183;
wire    ap_CS_fsm_state11;
wire   [31:0] grp_fu_368_p2;
reg   [31:0] value_assign_reg_1190;
wire    ap_CS_fsm_state36;
reg   [0:0] tmp_15_reg_1197;
wire    ap_CS_fsm_state37;
wire   [63:0] conv_i_fu_384_p1;
reg   [63:0] conv_i_reg_1202;
wire    ap_CS_fsm_state38;
wire   [63:0] select_ln2774_fu_848_p3;
reg   [63:0] select_ln2774_reg_1207;
wire   [31:0] result_V_20_fu_861_p3;
reg   [31:0] result_V_20_reg_1212;
wire    ap_CS_fsm_state40;
wire   [31:0] result_V_21_fu_873_p3;
reg   [31:0] result_V_21_reg_1218;
wire   [26:0] x_ratio_fu_901_p2;
reg   [26:0] x_ratio_reg_1224;
wire   [23:0] y_ratio_fu_925_p2;
reg   [23:0] y_ratio_reg_1229;
wire   [63:0] grp_fu_398_p2;
reg   [63:0] dc_reg_1234;
wire    ap_CS_fsm_state41;
wire   [31:0] result_V_19_fu_1063_p3;
reg   [31:0] result_V_19_reg_1239;
wire    ap_CS_fsm_state42;
reg   [6:0] result_x_Scale_address0;
reg    result_x_Scale_ce0;
reg    result_x_Scale_we0;
wire   [31:0] result_x_Scale_q0;
reg   [6:0] result_y_Scale_address0;
reg    result_y_Scale_ce0;
reg    result_y_Scale_we0;
wire   [31:0] result_y_Scale_q0;
reg   [6:0] result_w_Scale_address0;
reg    result_w_Scale_ce0;
reg    result_w_Scale_we0;
wire   [31:0] result_w_Scale_q0;
reg   [6:0] result_h_Scale_address0;
reg    result_h_Scale_ce0;
reg    result_h_Scale_we0;
wire   [31:0] result_h_Scale_q0;
reg   [16:0] IMG1_data_address0;
reg    IMG1_data_ce0;
reg    IMG1_data_we0;
wire   [7:0] IMG1_data_q0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_done;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_idle;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_ready;
wire   [8:0] grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_ce0;
wire   [16:0] grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_we0;
wire   [7:0] grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_d0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_idle;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_ready;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_d0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_idle;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_ready;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_ce0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_ce0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_ce0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_d0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_ce0;
wire   [6:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_address0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_ce0;
wire    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_we0;
wire   [31:0] grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_d0;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_done;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_idle;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_ready;
wire   [16:0] grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_address0;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_ce0;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_we0;
wire   [7:0] grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_d0;
wire   [16:0] grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_address0;
wire    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_ce0;
wire    grp_processImage_fu_310_ap_start;
wire    grp_processImage_fu_310_ap_done;
wire    grp_processImage_fu_310_ap_idle;
wire    grp_processImage_fu_310_ap_ready;
wire   [6:0] grp_processImage_fu_310_AllCandidates_x_address0;
wire    grp_processImage_fu_310_AllCandidates_x_ce0;
wire    grp_processImage_fu_310_AllCandidates_x_we0;
wire   [31:0] grp_processImage_fu_310_AllCandidates_x_d0;
wire   [6:0] grp_processImage_fu_310_AllCandidates_y_address0;
wire    grp_processImage_fu_310_AllCandidates_y_ce0;
wire    grp_processImage_fu_310_AllCandidates_y_we0;
wire   [31:0] grp_processImage_fu_310_AllCandidates_y_d0;
wire   [6:0] grp_processImage_fu_310_AllCandidates_w_address0;
wire    grp_processImage_fu_310_AllCandidates_w_ce0;
wire    grp_processImage_fu_310_AllCandidates_w_we0;
wire   [31:0] grp_processImage_fu_310_AllCandidates_w_d0;
wire   [6:0] grp_processImage_fu_310_AllCandidates_h_address0;
wire    grp_processImage_fu_310_AllCandidates_h_ce0;
wire    grp_processImage_fu_310_AllCandidates_h_we0;
wire   [31:0] grp_processImage_fu_310_AllCandidates_h_d0;
wire   [16:0] grp_processImage_fu_310_IMG1_data_address0;
wire    grp_processImage_fu_310_IMG1_data_ce0;
wire   [31:0] grp_processImage_fu_310_ap_return;
wire   [31:0] grp_processImage_fu_310_grp_fu_368_p_din0;
wire   [31:0] grp_processImage_fu_310_grp_fu_368_p_din1;
wire    grp_processImage_fu_310_grp_fu_368_p_ce;
wire   [63:0] grp_processImage_fu_310_grp_fu_398_p_din0;
wire   [63:0] grp_processImage_fu_310_grp_fu_398_p_din1;
wire   [1:0] grp_processImage_fu_310_grp_fu_398_p_opcode;
wire    grp_processImage_fu_310_grp_fu_398_p_ce;
reg   [31:0] counter_new_0_reg_239;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state45;
reg   [31:0] storemerge_reg_250;
reg    grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg;
reg    grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
wire   [0:0] icmp_ln2809_fu_448_p2;
reg    grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg;
reg    grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg;
reg    grp_processImage_fu_310_ap_start_reg;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state46;
reg   [31:0] factor_fu_224;
reg   [31:0] res_size_Scale_1_fu_228;
reg   [31:0] grp_fu_368_p0;
reg   [31:0] grp_fu_368_p1;
wire    ap_CS_fsm_state35;
reg   [31:0] grp_fu_387_p0;
reg   [31:0] grp_fu_387_p1;
reg   [63:0] grp_fu_398_p0;
reg   [63:0] grp_fu_398_p1;
wire    ap_CS_fsm_state39;
wire   [8:0] trunc_ln2804_1_fu_410_p1;
wire   [10:0] trunc_ln2804_fu_406_p1;
wire   [16:0] tmp_10_fu_420_p3;
wire   [16:0] tmp_11_fu_428_p3;
wire   [31:0] data_V_2_fu_472_p1;
wire   [7:0] tmp_fu_475_p4;
wire   [22:0] p_Result_6_fu_485_p1;
wire   [0:0] icmp_ln2838_1_fu_495_p2;
wire   [0:0] icmp_ln2838_fu_489_p2;
wire   [0:0] or_ln2838_fu_501_p2;
wire   [31:0] data_V_3_fu_512_p1;
wire   [7:0] tmp_12_fu_515_p4;
wire   [0:0] icmp_ln2838_3_fu_535_p2;
wire   [0:0] icmp_ln2838_2_fu_529_p2;
wire   [0:0] or_ln2838_1_fu_541_p2;
wire   [0:0] and_ln2838_1_fu_507_p2;
wire   [0:0] and_ln2838_2_fu_547_p2;
wire   [24:0] mantissa_2_fu_576_p4;
wire   [7:0] xs_exp_V_2_fu_566_p4;
wire   [8:0] zext_ln346_fu_590_p1;
wire   [8:0] add_ln346_fu_594_p2;
wire   [7:0] sub_ln1512_2_fu_608_p2;
wire   [0:0] isNeg_2_fu_600_p3;
wire  signed [8:0] sext_ln1512_2_fu_614_p1;
wire   [8:0] ush_2_fu_618_p3;
wire  signed [31:0] sext_ln1488_2_fu_626_p1;
wire   [78:0] zext_ln15_2_fu_586_p1;
wire   [78:0] zext_ln1488_3_fu_630_p1;
wire   [78:0] r_V_16_fu_634_p2;
wire   [0:0] tmp_22_fu_646_p3;
wire   [78:0] r_V_17_fu_640_p2;
wire   [31:0] zext_ln818_fu_654_p1;
wire   [31:0] tmp_16_fu_658_p4;
wire   [26:0] grp_fu_694_p0;
wire   [31:0] grp_fu_694_p1;
wire   [24:0] mantissa_3_fu_700_p4;
wire   [8:0] zext_ln346_1_fu_713_p1;
wire   [8:0] add_ln346_1_fu_716_p2;
wire   [7:0] sub_ln1512_3_fu_730_p2;
wire   [0:0] isNeg_3_fu_722_p3;
wire  signed [8:0] sext_ln1512_3_fu_735_p1;
wire   [8:0] ush_3_fu_739_p3;
wire  signed [31:0] sext_ln1488_3_fu_747_p1;
wire   [78:0] zext_ln15_3_fu_709_p1;
wire   [78:0] zext_ln1488_4_fu_751_p1;
wire   [78:0] r_V_18_fu_755_p2;
wire   [0:0] tmp_26_fu_767_p3;
wire   [78:0] r_V_19_fu_761_p2;
wire   [31:0] zext_ln818_2_fu_775_p1;
wire   [31:0] tmp_17_fu_779_p4;
wire   [25:0] grp_fu_797_p0;
wire   [31:0] grp_fu_797_p1;
wire   [31:0] bitcast_ln2774_fu_808_p1;
wire   [7:0] tmp_14_fu_811_p4;
wire   [22:0] trunc_ln2774_fu_821_p1;
wire   [0:0] icmp_ln2774_4_fu_831_p2;
wire   [0:0] icmp_ln2774_fu_825_p2;
wire   [0:0] or_ln2774_fu_837_p2;
wire   [0:0] and_ln2774_fu_843_p2;
wire   [31:0] result_V_13_fu_856_p2;
wire   [31:0] result_V_17_fu_868_p2;
wire   [25:0] grp_fu_694_p2;
wire   [25:0] trunc_ln3379_fu_880_p1;
wire  signed [26:0] sext_ln3379_fu_884_p1;
wire   [26:0] sub_ln3379_fu_888_p2;
wire   [26:0] select_ln3379_fu_894_p3;
wire   [23:0] grp_fu_797_p2;
wire   [23:0] trunc_ln3380_fu_908_p1;
wire   [23:0] sub_ln3380_fu_912_p2;
wire   [23:0] select_ln3380_fu_918_p3;
wire   [63:0] data_V_fu_932_p1;
wire   [51:0] p_Result_4_fu_945_p1;
wire   [53:0] mantissa_fu_949_p4;
wire   [10:0] xs_exp_V_fu_935_p4;
wire   [11:0] zext_ln515_fu_963_p1;
wire   [11:0] add_ln515_fu_967_p2;
wire   [10:0] sub_ln1512_fu_981_p2;
wire   [0:0] isNeg_fu_973_p3;
wire  signed [11:0] sext_ln1512_fu_987_p1;
wire   [11:0] ush_fu_991_p3;
wire  signed [31:0] sext_ln1488_fu_999_p1;
wire   [136:0] zext_ln15_fu_959_p1;
wire   [136:0] zext_ln1488_fu_1003_p1;
wire   [136:0] r_V_fu_1007_p2;
wire   [0:0] tmp_27_fu_1019_p3;
wire   [136:0] r_V_15_fu_1013_p2;
wire   [31:0] zext_ln818_3_fu_1027_p1;
wire   [31:0] tmp_28_fu_1031_p4;
wire   [31:0] val_fu_1041_p3;
wire   [0:0] p_Result_s_fu_1055_p3;
wire   [31:0] result_V_fu_1049_p2;
reg    grp_fu_368_ce;
reg   [4:0] grp_fu_387_opcode;
reg    grp_fu_398_ce;
reg    grp_fu_694_ap_start;
wire    grp_fu_694_ap_done;
reg    grp_fu_797_ap_start;
wire    grp_fu_797_ap_done;
reg   [45:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
reg    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
reg    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 46'd1;
#0 counter = 32'd0;
#0 grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg = 1'b0;
#0 grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg = 1'b0;
#0 grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg = 1'b0;
#0 grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg = 1'b0;
#0 grp_processImage_fu_310_ap_start_reg = 1'b0;
end

face_detect_Data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
Data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Data_address0),
    .ce0(Data_ce0),
    .we0(Data_we0),
    .d0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_d0),
    .q0(Data_q0)
);

face_detect_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_x_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_x_Scale_address0),
    .ce0(result_x_Scale_ce0),
    .we0(result_x_Scale_we0),
    .d0(grp_processImage_fu_310_AllCandidates_x_d0),
    .q0(result_x_Scale_q0)
);

face_detect_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_y_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_y_Scale_address0),
    .ce0(result_y_Scale_ce0),
    .we0(result_y_Scale_we0),
    .d0(grp_processImage_fu_310_AllCandidates_y_d0),
    .q0(result_y_Scale_q0)
);

face_detect_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_w_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_w_Scale_address0),
    .ce0(result_w_Scale_ce0),
    .we0(result_w_Scale_we0),
    .d0(grp_processImage_fu_310_AllCandidates_w_d0),
    .q0(result_w_Scale_q0)
);

face_detect_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_h_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_h_Scale_address0),
    .ce0(result_h_Scale_ce0),
    .we0(result_h_Scale_we0),
    .d0(grp_processImage_fu_310_AllCandidates_h_d0),
    .q0(result_h_Scale_q0)
);

face_detect_IMG1_data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
IMG1_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(IMG1_data_address0),
    .ce0(IMG1_data_ce0),
    .we0(IMG1_data_we0),
    .d0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_d0),
    .q0(IMG1_data_q0)
);

face_detect_face_detect_Pipeline_VITIS_LOOP_2805_1 grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start),
    .ap_done(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_done),
    .ap_idle(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_idle),
    .ap_ready(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_ready),
    .add_ln2806(add_ln2806_reg_1090),
    .inData_address0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_address0),
    .inData_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_ce0),
    .inData_q0(inData_q0),
    .Data_address0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_address0),
    .Data_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_ce0),
    .Data_we0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_we0),
    .Data_d0(grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_d0)
);

face_detect_face_detect_Pipeline_VITIS_LOOP_2810_2 grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start),
    .ap_done(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done),
    .ap_idle(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_idle),
    .ap_ready(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_ready),
    .result_x_address0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_address0),
    .result_x_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_ce0),
    .result_x_we0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_we0),
    .result_x_d0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_d0),
    .result_y_address0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_address0),
    .result_y_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_ce0),
    .result_y_we0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_we0),
    .result_y_d0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_d0),
    .result_w_address0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_address0),
    .result_w_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_ce0),
    .result_w_we0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_we0),
    .result_w_d0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_d0),
    .result_h_address0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_address0),
    .result_h_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_ce0),
    .result_h_we0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_we0),
    .result_h_d0(grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_d0)
);

face_detect_face_detect_Pipeline_VITIS_LOOP_2872_3 grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start),
    .ap_done(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done),
    .ap_idle(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_idle),
    .ap_ready(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_ready),
    .result_x_Scale_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_address0),
    .result_x_Scale_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_ce0),
    .result_x_Scale_q0(result_x_Scale_q0),
    .result_x_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_address0),
    .result_x_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_ce0),
    .result_x_we0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_we0),
    .result_x_d0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_d0),
    .result_y_Scale_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_address0),
    .result_y_Scale_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_ce0),
    .result_y_Scale_q0(result_y_Scale_q0),
    .result_y_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_address0),
    .result_y_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_ce0),
    .result_y_we0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_we0),
    .result_y_d0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_d0),
    .result_w_Scale_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_address0),
    .result_w_Scale_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_ce0),
    .result_w_Scale_q0(result_w_Scale_q0),
    .result_w_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_address0),
    .result_w_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_ce0),
    .result_w_we0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_we0),
    .result_w_d0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_d0),
    .result_h_Scale_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_address0),
    .result_h_Scale_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_ce0),
    .result_h_Scale_q0(result_h_Scale_q0),
    .result_h_address0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_address0),
    .result_h_ce0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_ce0),
    .result_h_we0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_we0),
    .result_h_d0(grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_d0)
);

face_detect_face_detect_Pipeline_imageScalerL1_imageScalerL1_1 grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start),
    .ap_done(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_done),
    .ap_idle(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_idle),
    .ap_ready(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_ready),
    .result_V_16(result_V_21_reg_1218),
    .y_ratio(y_ratio_reg_1229),
    .IMG1_data_address0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_address0),
    .IMG1_data_ce0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_ce0),
    .IMG1_data_we0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_we0),
    .IMG1_data_d0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_d0),
    .result_V_15(result_V_20_reg_1212),
    .sext_ln3379_2(x_ratio_reg_1224),
    .Data_address0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_address0),
    .Data_ce0(grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_ce0),
    .Data_q0(Data_q0)
);

face_detect_processImage grp_processImage_fu_310(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_processImage_fu_310_ap_start),
    .ap_done(grp_processImage_fu_310_ap_done),
    .ap_idle(grp_processImage_fu_310_ap_idle),
    .ap_ready(grp_processImage_fu_310_ap_ready),
    .factor(factor_2_reg_1117),
    .sum_row(result_V_21_reg_1218),
    .sum_col(result_V_20_reg_1212),
    .AllCandidates_x_address0(grp_processImage_fu_310_AllCandidates_x_address0),
    .AllCandidates_x_ce0(grp_processImage_fu_310_AllCandidates_x_ce0),
    .AllCandidates_x_we0(grp_processImage_fu_310_AllCandidates_x_we0),
    .AllCandidates_x_d0(grp_processImage_fu_310_AllCandidates_x_d0),
    .AllCandidates_y_address0(grp_processImage_fu_310_AllCandidates_y_address0),
    .AllCandidates_y_ce0(grp_processImage_fu_310_AllCandidates_y_ce0),
    .AllCandidates_y_we0(grp_processImage_fu_310_AllCandidates_y_we0),
    .AllCandidates_y_d0(grp_processImage_fu_310_AllCandidates_y_d0),
    .AllCandidates_w_address0(grp_processImage_fu_310_AllCandidates_w_address0),
    .AllCandidates_w_ce0(grp_processImage_fu_310_AllCandidates_w_ce0),
    .AllCandidates_w_we0(grp_processImage_fu_310_AllCandidates_w_we0),
    .AllCandidates_w_d0(grp_processImage_fu_310_AllCandidates_w_d0),
    .AllCandidates_h_address0(grp_processImage_fu_310_AllCandidates_h_address0),
    .AllCandidates_h_ce0(grp_processImage_fu_310_AllCandidates_h_ce0),
    .AllCandidates_h_we0(grp_processImage_fu_310_AllCandidates_h_we0),
    .AllCandidates_h_d0(grp_processImage_fu_310_AllCandidates_h_d0),
    .AllCandidates_size_read(res_size_Scale_1_fu_228),
    .IMG1_data_address0(grp_processImage_fu_310_IMG1_data_address0),
    .IMG1_data_ce0(grp_processImage_fu_310_IMG1_data_ce0),
    .IMG1_data_q0(IMG1_data_q0),
    .winSize_width(result_V_19_reg_1239),
    .ap_return(grp_processImage_fu_310_ap_return),
    .grp_fu_368_p_din0(grp_processImage_fu_310_grp_fu_368_p_din0),
    .grp_fu_368_p_din1(grp_processImage_fu_310_grp_fu_368_p_din1),
    .grp_fu_368_p_dout0(grp_fu_368_p2),
    .grp_fu_368_p_ce(grp_processImage_fu_310_grp_fu_368_p_ce),
    .grp_fu_398_p_din0(grp_processImage_fu_310_grp_fu_398_p_din0),
    .grp_fu_398_p_din1(grp_processImage_fu_310_grp_fu_398_p_din1),
    .grp_fu_398_p_opcode(grp_processImage_fu_310_grp_fu_398_p_opcode),
    .grp_fu_398_p_dout0(grp_fu_398_p2),
    .grp_fu_398_p_ce(grp_processImage_fu_310_grp_fu_398_p_ce)
);

face_detect_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U2826(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_368_p0),
    .din1(grp_fu_368_p1),
    .ce(grp_fu_368_ce),
    .dout(grp_fu_368_p2)
);

face_detect_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U2827(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1134559232),
    .din1(factor_fu_224),
    .ce(1'b1),
    .dout(grp_fu_374_p2)
);

face_detect_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U2828(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1131413504),
    .din1(factor_fu_224),
    .ce(1'b1),
    .dout(grp_fu_379_p2)
);

face_detect_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U2829(
    .din0(value_assign_reg_1190),
    .dout(conv_i_fu_384_p1)
);

face_detect_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U2830(
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .opcode(grp_fu_387_opcode),
    .dout(grp_fu_387_p2)
);

face_detect_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U2831(
    .din0(dc_3_reg_1129),
    .din1(32'd1103626240),
    .opcode(5'd2),
    .dout(tmp_13_fu_392_p2)
);

face_detect_dadd_64ns_64ns_64_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_3_full_dsp_1_U2832(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_398_p0),
    .din1(grp_fu_398_p1),
    .ce(grp_fu_398_ce),
    .dout(grp_fu_398_p2)
);

face_detect_sdiv_27ns_32ns_26_31_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 26 ))
sdiv_27ns_32ns_26_31_seq_1_U2833(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_694_ap_start),
    .done(grp_fu_694_ap_done),
    .din0(grp_fu_694_p0),
    .din1(grp_fu_694_p1),
    .ce(1'b1),
    .dout(grp_fu_694_p2)
);

face_detect_sdiv_26ns_32ns_24_30_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 30 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 24 ))
sdiv_26ns_32ns_24_30_seq_1_U2834(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_797_ap_start),
    .done(grp_fu_797_ap_done),
    .din0(grp_fu_797_p0),
    .din1(grp_fu_797_p1),
    .ce(1'b1),
    .dout(grp_fu_797_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln2804_fu_414_p2 == 1'd1))) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_ready == 1'b1)) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln2809_fu_448_p2 == 1'd1) & (1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg <= 1'b1;
        end else if ((grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_ready == 1'b1)) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd0 == and_ln2838_fu_552_p2) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_ready == 1'b1)) begin
            grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state40)) begin
            grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg <= 1'b1;
        end else if ((grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_ready == 1'b1)) begin
            grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_processImage_fu_310_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state42)) begin
            grp_processImage_fu_310_ap_start_reg <= 1'b1;
        end else if ((grp_processImage_fu_310_ap_ready == 1'b1)) begin
            grp_processImage_fu_310_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
        counter_new_0_reg_239 <= add_ln2808_reg_1095;
    end else if (((grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        counter_new_0_reg_239 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2809_fu_448_p2 == 1'd0) | (icmp_ln2804_reg_1086 == 1'd0)))) begin
        factor_fu_224 <= 32'd1067030938;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        factor_fu_224 <= grp_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2809_fu_448_p2 == 1'd0) | (icmp_ln2804_reg_1086 == 1'd0)))) begin
        res_size_Scale_1_fu_228 <= 32'd0;
    end else if (((grp_processImage_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
        res_size_Scale_1_fu_228 <= grp_processImage_fu_310_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
        storemerge_reg_250 <= 32'd0;
    end else if (((grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        storemerge_reg_250 <= res_size_Scale_1_load_reg_1145;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln2804_fu_414_p2 == 1'd1))) begin
        add_ln2806_reg_1090[16 : 6] <= add_ln2806_fu_436_p2[16 : 6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
        add_ln2808_reg_1095 <= add_ln2808_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        conv_i_reg_1202 <= conv_i_fu_384_p1;
        select_ln2774_reg_1207[63] <= select_ln2774_fu_848_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        counter <= counter_new_0_reg_239;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dc_2_reg_1123 <= grp_fu_374_p2;
        dc_3_reg_1129 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        dc_reg_1234 <= grp_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        factor_2_reg_1117 <= factor_fu_224;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln2804_reg_1086 <= icmp_ln2804_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln2838_fu_552_p2))) begin
        p_Result_5_reg_1158 <= data_V_2_fu_472_p1[32'd31];
        p_Result_7_reg_1171 <= data_V_3_fu_512_p1[32'd31];
        val_2_reg_1164 <= val_2_fu_668_p3;
        xs_exp_V_3_reg_1177 <= {{data_V_3_fu_512_p1[30:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_Result_8_reg_1150 <= p_Result_8_fu_525_p1;
        res_size_Scale_1_load_reg_1145 <= res_size_Scale_1_fu_228;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        result_V_19_reg_1239 <= result_V_19_fu_1063_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        result_V_20_reg_1212 <= result_V_20_fu_861_p3;
        result_V_21_reg_1218 <= result_V_21_fu_873_p3;
        x_ratio_reg_1224 <= x_ratio_fu_901_p2;
        y_ratio_reg_1229 <= y_ratio_fu_925_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_13_reg_1140 <= tmp_13_fu_392_p2;
        tmp_s_reg_1135 <= grp_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        tmp_15_reg_1197 <= grp_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        val_3_reg_1183 <= val_3_fu_789_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        value_assign_reg_1190 <= grp_fu_368_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        Data_address0 = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
        Data_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_address0;
    end else begin
        Data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        Data_ce0 = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_Data_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
        Data_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_ce0;
    end else begin
        Data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
        Data_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_Data_we0;
    end else begin
        Data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        IMG1_data_address0 = grp_processImage_fu_310_IMG1_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        IMG1_data_address0 = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_address0;
    end else begin
        IMG1_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        IMG1_data_ce0 = grp_processImage_fu_310_IMG1_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        IMG1_data_ce0 = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_ce0;
    end else begin
        IMG1_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        IMG1_data_we0 = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_IMG1_data_we0;
    end else begin
        IMG1_data_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

always @ (*) begin
    if ((grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_done == 1'b0)) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

assign ap_ST_fsm_state42_blk = 1'b0;

always @ (*) begin
    if ((grp_processImage_fu_310_ap_done == 1'b0)) begin
        ap_ST_fsm_state43_blk = 1'b1;
    end else begin
        ap_ST_fsm_state43_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done == 1'b0)) begin
        ap_ST_fsm_state45_blk = 1'b1;
    end else begin
        ap_ST_fsm_state45_blk = 1'b0;
    end
end

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_368_ce = grp_processImage_fu_310_grp_fu_368_p_ce;
    end else begin
        grp_fu_368_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_368_p0 = grp_processImage_fu_310_grp_fu_368_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_368_p0 = factor_2_reg_1117;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_368_p0 = factor_fu_224;
    end else begin
        grp_fu_368_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_368_p1 = grp_processImage_fu_310_grp_fu_368_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_368_p1 = 32'd1103101952;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_368_p1 = 32'd1067030938;
    end else begin
        grp_fu_368_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_fu_387_opcode = 5'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_387_opcode = 5'd2;
    end else begin
        grp_fu_387_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_fu_387_p0 = value_assign_reg_1190;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_387_p0 = dc_2_reg_1123;
    end else begin
        grp_fu_387_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_fu_387_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_387_p1 = 32'd1103626240;
    end else begin
        grp_fu_387_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_398_ce = grp_processImage_fu_310_grp_fu_398_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state40) | ((grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41)))) begin
        grp_fu_398_ce = 1'b1;
    end else begin
        grp_fu_398_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_398_p0 = grp_processImage_fu_310_grp_fu_398_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_398_p0 = conv_i_reg_1202;
    end else begin
        grp_fu_398_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_398_p1 = grp_processImage_fu_310_grp_fu_398_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_398_p1 = select_ln2774_reg_1207;
    end else begin
        grp_fu_398_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln2838_fu_552_p2))) begin
        grp_fu_694_ap_start = 1'b1;
    end else begin
        grp_fu_694_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_797_ap_start = 1'b1;
    end else begin
        grp_fu_797_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_h_Scale_address0 = grp_processImage_fu_310_AllCandidates_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_Scale_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_address0;
    end else begin
        result_h_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_h_Scale_ce0 = grp_processImage_fu_310_AllCandidates_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_Scale_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_Scale_ce0;
    end else begin
        result_h_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_h_Scale_we0 = grp_processImage_fu_310_AllCandidates_h_we0;
    end else begin
        result_h_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_h_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_address0;
    end else begin
        result_h_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_h_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_ce0;
    end else begin
        result_h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_d0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_h_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_d0;
    end else begin
        result_h_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_h_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_h_we0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_h_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_h_we0;
    end else begin
        result_h_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        result_size_ap_vld = 1'b1;
    end else begin
        result_size_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_w_Scale_address0 = grp_processImage_fu_310_AllCandidates_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_Scale_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_address0;
    end else begin
        result_w_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_w_Scale_ce0 = grp_processImage_fu_310_AllCandidates_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_Scale_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_Scale_ce0;
    end else begin
        result_w_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_w_Scale_we0 = grp_processImage_fu_310_AllCandidates_w_we0;
    end else begin
        result_w_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_w_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_address0;
    end else begin
        result_w_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_w_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_ce0;
    end else begin
        result_w_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_d0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_w_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_d0;
    end else begin
        result_w_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_w_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_w_we0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_w_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_w_we0;
    end else begin
        result_w_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_x_Scale_address0 = grp_processImage_fu_310_AllCandidates_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_Scale_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_address0;
    end else begin
        result_x_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_x_Scale_ce0 = grp_processImage_fu_310_AllCandidates_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_Scale_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_Scale_ce0;
    end else begin
        result_x_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_x_Scale_we0 = grp_processImage_fu_310_AllCandidates_x_we0;
    end else begin
        result_x_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_x_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_address0;
    end else begin
        result_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_x_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_ce0;
    end else begin
        result_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_d0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_x_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_d0;
    end else begin
        result_x_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_x_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_x_we0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_x_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_x_we0;
    end else begin
        result_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_y_Scale_address0 = grp_processImage_fu_310_AllCandidates_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_Scale_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_address0;
    end else begin
        result_y_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_y_Scale_ce0 = grp_processImage_fu_310_AllCandidates_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_Scale_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_Scale_ce0;
    end else begin
        result_y_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        result_y_Scale_we0 = grp_processImage_fu_310_AllCandidates_y_we0;
    end else begin
        result_y_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_y_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_address0;
    end else begin
        result_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_y_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_ce0;
    end else begin
        result_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_y_d0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_d0;
    end else begin
        result_y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        result_y_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_result_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        result_y_we0 = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_result_y_we0;
    end else begin
        result_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2809_fu_448_p2 == 1'd0) | (icmp_ln2804_reg_1086 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((icmp_ln2809_fu_448_p2 == 1'd1) & (1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln2804_reg_1086 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'd0 == and_ln2838_fu_552_p2) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            if (((grp_processImage_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state44 : begin
            if (((grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state45 : begin
            if (((grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2806_fu_436_p2 = (tmp_10_fu_420_p3 + tmp_11_fu_428_p3);

assign add_ln2808_fu_443_p2 = (counter + 32'd1);

assign add_ln346_1_fu_716_p2 = ($signed(zext_ln346_1_fu_713_p1) + $signed(9'd385));

assign add_ln346_fu_594_p2 = ($signed(zext_ln346_fu_590_p1) + $signed(9'd385));

assign add_ln515_fu_967_p2 = ($signed(zext_ln515_fu_963_p1) + $signed(12'd3073));

assign and_ln2774_fu_843_p2 = (tmp_15_reg_1197 & or_ln2774_fu_837_p2);

assign and_ln2838_1_fu_507_p2 = (tmp_s_reg_1135 & or_ln2838_fu_501_p2);

assign and_ln2838_2_fu_547_p2 = (tmp_13_reg_1140 & or_ln2838_1_fu_541_p2);

assign and_ln2838_fu_552_p2 = (and_ln2838_2_fu_547_p2 & and_ln2838_1_fu_507_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_done == 1'b0) & (icmp_ln2804_reg_1086 == 1'd1));
end

assign bitcast_ln2774_fu_808_p1 = value_assign_reg_1190;

assign data_V_2_fu_472_p1 = dc_2_reg_1123;

assign data_V_3_fu_512_p1 = dc_3_reg_1129;

assign data_V_fu_932_p1 = dc_reg_1234;

assign grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_ap_start_reg;

assign grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start = grp_face_detect_Pipeline_VITIS_LOOP_2810_2_fu_271_ap_start_reg;

assign grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start = grp_face_detect_Pipeline_VITIS_LOOP_2872_3_fu_283_ap_start_reg;

assign grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start = grp_face_detect_Pipeline_imageScalerL1_imageScalerL1_1_fu_299_ap_start_reg;

assign grp_fu_694_p0 = 32'd20971520;

assign grp_fu_694_p1 = ((isNeg_2_fu_600_p3[0:0] == 1'b1) ? zext_ln818_fu_654_p1 : tmp_16_fu_658_p4);

assign grp_fu_797_p0 = 32'd15728640;

assign grp_fu_797_p1 = ((isNeg_3_fu_722_p3[0:0] == 1'b1) ? zext_ln818_2_fu_775_p1 : tmp_17_fu_779_p4);

assign grp_processImage_fu_310_ap_start = grp_processImage_fu_310_ap_start_reg;

assign icmp_ln2774_4_fu_831_p2 = ((trunc_ln2774_fu_821_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2774_fu_825_p2 = ((tmp_14_fu_811_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln2804_fu_414_p2 = (($signed(counter) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign icmp_ln2809_fu_448_p2 = (($signed(add_ln2808_fu_443_p2) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign icmp_ln2838_1_fu_495_p2 = ((p_Result_6_fu_485_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2838_2_fu_529_p2 = ((tmp_12_fu_515_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln2838_3_fu_535_p2 = ((p_Result_8_fu_525_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2838_fu_489_p2 = ((tmp_fu_475_p4 != 8'd255) ? 1'b1 : 1'b0);

assign inData_address0 = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_address0;

assign inData_ce0 = grp_face_detect_Pipeline_VITIS_LOOP_2805_1_fu_262_inData_ce0;

assign isNeg_2_fu_600_p3 = add_ln346_fu_594_p2[32'd8];

assign isNeg_3_fu_722_p3 = add_ln346_1_fu_716_p2[32'd8];

assign isNeg_fu_973_p3 = add_ln515_fu_967_p2[32'd11];

assign mantissa_2_fu_576_p4 = {{{{1'd1}, {p_Result_6_fu_485_p1}}}, {1'd0}};

assign mantissa_3_fu_700_p4 = {{{{1'd1}, {p_Result_8_reg_1150}}}, {1'd0}};

assign mantissa_fu_949_p4 = {{{{1'd1}, {p_Result_4_fu_945_p1}}}, {1'd0}};

assign or_ln2774_fu_837_p2 = (icmp_ln2774_fu_825_p2 | icmp_ln2774_4_fu_831_p2);

assign or_ln2838_1_fu_541_p2 = (icmp_ln2838_3_fu_535_p2 | icmp_ln2838_2_fu_529_p2);

assign or_ln2838_fu_501_p2 = (icmp_ln2838_fu_489_p2 | icmp_ln2838_1_fu_495_p2);

assign p_Result_4_fu_945_p1 = data_V_fu_932_p1[51:0];

assign p_Result_6_fu_485_p1 = data_V_2_fu_472_p1[22:0];

assign p_Result_8_fu_525_p1 = data_V_3_fu_512_p1[22:0];

assign p_Result_s_fu_1055_p3 = data_V_fu_932_p1[32'd63];

assign r_V_15_fu_1013_p2 = zext_ln15_fu_959_p1 << zext_ln1488_fu_1003_p1;

assign r_V_16_fu_634_p2 = zext_ln15_2_fu_586_p1 >> zext_ln1488_3_fu_630_p1;

assign r_V_17_fu_640_p2 = zext_ln15_2_fu_586_p1 << zext_ln1488_3_fu_630_p1;

assign r_V_18_fu_755_p2 = zext_ln15_3_fu_709_p1 >> zext_ln1488_4_fu_751_p1;

assign r_V_19_fu_761_p2 = zext_ln15_3_fu_709_p1 << zext_ln1488_4_fu_751_p1;

assign r_V_fu_1007_p2 = zext_ln15_fu_959_p1 >> zext_ln1488_fu_1003_p1;

assign result_V_13_fu_856_p2 = (32'd0 - val_2_reg_1164);

assign result_V_17_fu_868_p2 = (32'd0 - val_3_reg_1183);

assign result_V_19_fu_1063_p3 = ((p_Result_s_fu_1055_p3[0:0] == 1'b1) ? result_V_fu_1049_p2 : val_fu_1041_p3);

assign result_V_20_fu_861_p3 = ((p_Result_5_reg_1158[0:0] == 1'b1) ? result_V_13_fu_856_p2 : val_2_reg_1164);

assign result_V_21_fu_873_p3 = ((p_Result_7_reg_1171[0:0] == 1'b1) ? result_V_17_fu_868_p2 : val_3_reg_1183);

assign result_V_fu_1049_p2 = (32'd0 - val_fu_1041_p3);

assign result_size = storemerge_reg_250;

assign select_ln2774_fu_848_p3 = ((and_ln2774_fu_843_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign select_ln3379_fu_894_p3 = ((p_Result_5_reg_1158[0:0] == 1'b1) ? sub_ln3379_fu_888_p2 : sext_ln3379_fu_884_p1);

assign select_ln3380_fu_918_p3 = ((p_Result_7_reg_1171[0:0] == 1'b1) ? sub_ln3380_fu_912_p2 : trunc_ln3380_fu_908_p1);

assign sext_ln1488_2_fu_626_p1 = $signed(ush_2_fu_618_p3);

assign sext_ln1488_3_fu_747_p1 = $signed(ush_3_fu_739_p3);

assign sext_ln1488_fu_999_p1 = $signed(ush_fu_991_p3);

assign sext_ln1512_2_fu_614_p1 = $signed(sub_ln1512_2_fu_608_p2);

assign sext_ln1512_3_fu_735_p1 = $signed(sub_ln1512_3_fu_730_p2);

assign sext_ln1512_fu_987_p1 = $signed(sub_ln1512_fu_981_p2);

assign sext_ln3379_fu_884_p1 = $signed(trunc_ln3379_fu_880_p1);

assign sub_ln1512_2_fu_608_p2 = (8'd127 - xs_exp_V_2_fu_566_p4);

assign sub_ln1512_3_fu_730_p2 = (8'd127 - xs_exp_V_3_reg_1177);

assign sub_ln1512_fu_981_p2 = (11'd1023 - xs_exp_V_fu_935_p4);

assign sub_ln3379_fu_888_p2 = ($signed(27'd0) - $signed(sext_ln3379_fu_884_p1));

assign sub_ln3380_fu_912_p2 = (24'd0 - trunc_ln3380_fu_908_p1);

assign tmp_10_fu_420_p3 = {{trunc_ln2804_1_fu_410_p1}, {8'd0}};

assign tmp_11_fu_428_p3 = {{trunc_ln2804_fu_406_p1}, {6'd0}};

assign tmp_12_fu_515_p4 = {{data_V_3_fu_512_p1[30:23]}};

assign tmp_14_fu_811_p4 = {{bitcast_ln2774_fu_808_p1[30:23]}};

assign tmp_16_fu_658_p4 = {{r_V_17_fu_640_p2[55:24]}};

assign tmp_17_fu_779_p4 = {{r_V_19_fu_761_p2[55:24]}};

assign tmp_22_fu_646_p3 = r_V_16_fu_634_p2[32'd24];

assign tmp_26_fu_767_p3 = r_V_18_fu_755_p2[32'd24];

assign tmp_27_fu_1019_p3 = r_V_fu_1007_p2[32'd53];

assign tmp_28_fu_1031_p4 = {{r_V_15_fu_1013_p2[84:53]}};

assign tmp_fu_475_p4 = {{data_V_2_fu_472_p1[30:23]}};

assign trunc_ln2774_fu_821_p1 = bitcast_ln2774_fu_808_p1[22:0];

assign trunc_ln2804_1_fu_410_p1 = counter[8:0];

assign trunc_ln2804_fu_406_p1 = counter[10:0];

assign trunc_ln3379_fu_880_p1 = grp_fu_694_p2[25:0];

assign trunc_ln3380_fu_908_p1 = grp_fu_797_p2[23:0];

assign ush_2_fu_618_p3 = ((isNeg_2_fu_600_p3[0:0] == 1'b1) ? sext_ln1512_2_fu_614_p1 : add_ln346_fu_594_p2);

assign ush_3_fu_739_p3 = ((isNeg_3_fu_722_p3[0:0] == 1'b1) ? sext_ln1512_3_fu_735_p1 : add_ln346_1_fu_716_p2);

assign ush_fu_991_p3 = ((isNeg_fu_973_p3[0:0] == 1'b1) ? sext_ln1512_fu_987_p1 : add_ln515_fu_967_p2);

assign val_2_fu_668_p3 = ((isNeg_2_fu_600_p3[0:0] == 1'b1) ? zext_ln818_fu_654_p1 : tmp_16_fu_658_p4);

assign val_3_fu_789_p3 = ((isNeg_3_fu_722_p3[0:0] == 1'b1) ? zext_ln818_2_fu_775_p1 : tmp_17_fu_779_p4);

assign val_fu_1041_p3 = ((isNeg_fu_973_p3[0:0] == 1'b1) ? zext_ln818_3_fu_1027_p1 : tmp_28_fu_1031_p4);

assign x_ratio_fu_901_p2 = (select_ln3379_fu_894_p3 + 27'd1);

assign xs_exp_V_2_fu_566_p4 = {{data_V_2_fu_472_p1[30:23]}};

assign xs_exp_V_fu_935_p4 = {{data_V_fu_932_p1[62:52]}};

assign y_ratio_fu_925_p2 = (select_ln3380_fu_918_p3 + 24'd1);

assign zext_ln1488_3_fu_630_p1 = $unsigned(sext_ln1488_2_fu_626_p1);

assign zext_ln1488_4_fu_751_p1 = $unsigned(sext_ln1488_3_fu_747_p1);

assign zext_ln1488_fu_1003_p1 = $unsigned(sext_ln1488_fu_999_p1);

assign zext_ln15_2_fu_586_p1 = mantissa_2_fu_576_p4;

assign zext_ln15_3_fu_709_p1 = mantissa_3_fu_700_p4;

assign zext_ln15_fu_959_p1 = mantissa_fu_949_p4;

assign zext_ln346_1_fu_713_p1 = xs_exp_V_3_reg_1177;

assign zext_ln346_fu_590_p1 = xs_exp_V_2_fu_566_p4;

assign zext_ln515_fu_963_p1 = xs_exp_V_fu_935_p4;

assign zext_ln818_2_fu_775_p1 = tmp_26_fu_767_p3;

assign zext_ln818_3_fu_1027_p1 = tmp_27_fu_1019_p3;

assign zext_ln818_fu_654_p1 = tmp_22_fu_646_p3;

always @ (posedge ap_clk) begin
    add_ln2806_reg_1090[5:0] <= 6'b000000;
    select_ln2774_reg_1207[62:0] <= 63'b011111111100000000000000000000000000000000000000000000000000000;
end

endmodule //face_detect
