// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rendering_projection (
        ap_ready,
        triangle_2d_x0_V_write,
        triangle_2d_y0_V_write,
        triangle_3d_z0,
        triangle_2d_x1_V_write,
        triangle_2d_y1_V_write,
        triangle_3d_z1,
        triangle_2d_x2_V_write,
        triangle_2d_y2_V_write,
        triangle_3d_z2,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [7:0] triangle_2d_x0_V_write;
input  [7:0] triangle_2d_y0_V_write;
input  [7:0] triangle_3d_z0;
input  [7:0] triangle_2d_x1_V_write;
input  [7:0] triangle_2d_y1_V_write;
input  [7:0] triangle_3d_z1;
input  [7:0] triangle_2d_x2_V_write;
input  [7:0] triangle_2d_y2_V_write;
input  [7:0] triangle_3d_z2;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;

wire   [7:0] mul_ln1513_fu_88_p0;
wire   [9:0] mul_ln1513_fu_88_p1;
wire   [16:0] mul_ln1513_fu_88_p2;
wire   [6:0] tmp_fu_94_p4;
wire   [7:0] mul_ln1513_1_fu_112_p0;
wire   [9:0] mul_ln1513_1_fu_112_p1;
wire   [16:0] mul_ln1513_1_fu_112_p2;
wire   [6:0] tmp_2_fu_118_p4;
wire   [7:0] mul_ln1513_2_fu_136_p0;
wire   [9:0] mul_ln1513_2_fu_136_p1;
wire   [16:0] mul_ln1513_2_fu_136_p2;
wire   [6:0] tmp_3_fu_142_p4;
wire   [7:0] zext_ln1513_1_fu_104_p1;
wire   [7:0] zext_ln1513_5_fu_152_p1;
wire   [7:0] add_ln186_fu_156_p2;
wire   [7:0] zext_ln1513_3_fu_128_p1;
wire   [7:0] add_ln186_1_fu_162_p2;
wire   [16:0] mul_ln1513_1_fu_112_p00;
wire   [16:0] mul_ln1513_2_fu_136_p00;
wire   [16:0] mul_ln1513_fu_88_p00;

rendering_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U1(
    .din0(mul_ln1513_fu_88_p0),
    .din1(mul_ln1513_fu_88_p1),
    .dout(mul_ln1513_fu_88_p2)
);

rendering_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U2(
    .din0(mul_ln1513_1_fu_112_p0),
    .din1(mul_ln1513_1_fu_112_p1),
    .dout(mul_ln1513_1_fu_112_p2)
);

rendering_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U3(
    .din0(mul_ln1513_2_fu_136_p0),
    .din1(mul_ln1513_2_fu_136_p1),
    .dout(mul_ln1513_2_fu_136_p2)
);

assign add_ln186_1_fu_162_p2 = (add_ln186_fu_156_p2 + zext_ln1513_3_fu_128_p1);

assign add_ln186_fu_156_p2 = (zext_ln1513_1_fu_104_p1 + zext_ln1513_5_fu_152_p1);

assign ap_ready = 1'b1;

assign mul_ln1513_1_fu_112_p00 = triangle_3d_z1;

assign mul_ln1513_2_fu_136_p00 = triangle_3d_z2;

assign mul_ln1513_fu_88_p00 = triangle_3d_z0;

assign tmp_2_fu_118_p4 = {{mul_ln1513_1_fu_112_p2[16:10]}};

assign tmp_3_fu_142_p4 = {{mul_ln1513_2_fu_136_p2[16:10]}};

assign tmp_fu_94_p4 = {{mul_ln1513_fu_88_p2[16:10]}};

assign zext_ln1513_1_fu_104_p1 = tmp_fu_94_p4;

assign zext_ln1513_3_fu_128_p1 = tmp_2_fu_118_p4;

assign zext_ln1513_5_fu_152_p1 = tmp_3_fu_142_p4;

assign ap_return_0 = triangle_2d_x0_V_write;

assign ap_return_1 = triangle_2d_y0_V_write;

assign ap_return_2 = triangle_2d_x1_V_write;

assign ap_return_3 = triangle_2d_y1_V_write;

assign ap_return_4 = triangle_2d_x2_V_write;

assign ap_return_5 = triangle_2d_y2_V_write;

assign ap_return_6 = add_ln186_1_fu_162_p2;

assign mul_ln1513_1_fu_112_p0 = mul_ln1513_1_fu_112_p00;

assign mul_ln1513_1_fu_112_p1 = 17'd342;

assign mul_ln1513_2_fu_136_p0 = mul_ln1513_2_fu_136_p00;

assign mul_ln1513_2_fu_136_p1 = 17'd342;

assign mul_ln1513_fu_88_p0 = mul_ln1513_fu_88_p00;

assign mul_ln1513_fu_88_p1 = 17'd342;

endmodule //rendering_projection
