set moduleName tensor_weight_y
set isTopModule 0
set isCombinational 0
set isDatapathOnly 0
set isPipelined 1
set pipeline_type none
set FunctionProtocol ap_ctrl_hs
set isOneStateSeq 0
set ProfileFlag 0
set StallSigGenFlag 0
set isEnableWaveformDebug 1
set hasInterrupt 0
set C_modelName {tensor_weight_y}
set C_modelType { void 0 }
set C_modelArgList {
	{ out_product int 192 regular {fifo 0 volatile } {global 0}  }
	{ tensor_y int 192 regular {fifo 1 volatile } {global 1}  }
}
set C_modelArgMapList {[ 
	{ "Name" : "out_product", "interface" : "fifo", "bitwidth" : 192, "direction" : "READONLY", "extern" : 0} , 
 	{ "Name" : "tensor_y", "interface" : "fifo", "bitwidth" : 192, "direction" : "WRITEONLY", "extern" : 0} ]}
# RTL Port declarations: 
set portNum 20
set portList { 
	{ ap_clk sc_in sc_logic 1 clock -1 } 
	{ ap_rst sc_in sc_logic 1 reset -1 active_high_sync } 
	{ ap_start sc_in sc_logic 1 start -1 } 
	{ start_full_n sc_in sc_logic 1 signal -1 } 
	{ ap_done sc_out sc_logic 1 predone -1 } 
	{ ap_continue sc_in sc_logic 1 continue -1 } 
	{ ap_idle sc_out sc_logic 1 done -1 } 
	{ ap_ready sc_out sc_logic 1 ready -1 } 
	{ out_product_dout sc_in sc_lv 192 signal 0 } 
	{ out_product_num_data_valid sc_in sc_lv 11 signal 0 } 
	{ out_product_fifo_cap sc_in sc_lv 11 signal 0 } 
	{ out_product_empty_n sc_in sc_logic 1 signal 0 } 
	{ out_product_read sc_out sc_logic 1 signal 0 } 
	{ tensor_y_din sc_out sc_lv 192 signal 1 } 
	{ tensor_y_num_data_valid sc_in sc_lv 11 signal 1 } 
	{ tensor_y_fifo_cap sc_in sc_lv 11 signal 1 } 
	{ tensor_y_full_n sc_in sc_logic 1 signal 1 } 
	{ tensor_y_write sc_out sc_logic 1 signal 1 } 
	{ start_out sc_out sc_logic 1 signal -1 } 
	{ start_write sc_out sc_logic 1 signal -1 } 
}
set NewPortList {[ 
	{ "name": "ap_clk", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "clock", "bundle":{"name": "ap_clk", "role": "default" }} , 
 	{ "name": "ap_rst", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "reset", "bundle":{"name": "ap_rst", "role": "default" }} , 
 	{ "name": "ap_start", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "start", "bundle":{"name": "ap_start", "role": "default" }} , 
 	{ "name": "start_full_n", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "start_full_n", "role": "default" }} , 
 	{ "name": "ap_done", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "predone", "bundle":{"name": "ap_done", "role": "default" }} , 
 	{ "name": "ap_continue", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "continue", "bundle":{"name": "ap_continue", "role": "default" }} , 
 	{ "name": "ap_idle", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "done", "bundle":{"name": "ap_idle", "role": "default" }} , 
 	{ "name": "ap_ready", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "ready", "bundle":{"name": "ap_ready", "role": "default" }} , 
 	{ "name": "out_product_dout", "direction": "in", "datatype": "sc_lv", "bitwidth":192, "type": "signal", "bundle":{"name": "out_product", "role": "dout" }} , 
 	{ "name": "out_product_num_data_valid", "direction": "in", "datatype": "sc_lv", "bitwidth":11, "type": "signal", "bundle":{"name": "out_product", "role": "num_data_valid" }} , 
 	{ "name": "out_product_fifo_cap", "direction": "in", "datatype": "sc_lv", "bitwidth":11, "type": "signal", "bundle":{"name": "out_product", "role": "fifo_cap" }} , 
 	{ "name": "out_product_empty_n", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "out_product", "role": "empty_n" }} , 
 	{ "name": "out_product_read", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "out_product", "role": "read" }} , 
 	{ "name": "tensor_y_din", "direction": "out", "datatype": "sc_lv", "bitwidth":192, "type": "signal", "bundle":{"name": "tensor_y", "role": "din" }} , 
 	{ "name": "tensor_y_num_data_valid", "direction": "in", "datatype": "sc_lv", "bitwidth":11, "type": "signal", "bundle":{"name": "tensor_y", "role": "num_data_valid" }} , 
 	{ "name": "tensor_y_fifo_cap", "direction": "in", "datatype": "sc_lv", "bitwidth":11, "type": "signal", "bundle":{"name": "tensor_y", "role": "fifo_cap" }} , 
 	{ "name": "tensor_y_full_n", "direction": "in", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "tensor_y", "role": "full_n" }} , 
 	{ "name": "tensor_y_write", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "tensor_y", "role": "write" }} , 
 	{ "name": "start_out", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "start_out", "role": "default" }} , 
 	{ "name": "start_write", "direction": "out", "datatype": "sc_logic", "bitwidth":1, "type": "signal", "bundle":{"name": "start_write", "role": "default" }}  ]}

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"],
		"CDFG" : "tensor_weight_y",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2684931", "EstimateLatencyMax" : "2684931",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"DependenceCheck" : [
			{"FromInitialState" : "ap_enable_state1_pp0_iter0_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_61", "FromInitialSV" : "0", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_74", "FromFinalSV" : "1", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state2_pp0_iter0_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_78", "ToInitialSV" : "1", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_78", "ToFinalSV" : "1", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state1_pp0_iter0_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_62", "FromInitialSV" : "0", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_76", "FromFinalSV" : "1", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state2_pp0_iter0_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_88", "ToInitialSV" : "1", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_88", "ToFinalSV" : "1", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state2_pp0_iter0_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_78", "FromInitialSV" : "1", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_78", "FromFinalSV" : "1", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state1_pp0_iter0_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_61", "ToInitialSV" : "0", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_74", "ToFinalSV" : "1", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state1_pp0_iter0_stage0"]},
			{"FromInitialState" : "ap_enable_state2_pp0_iter0_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_88", "FromInitialSV" : "1", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_88", "FromFinalSV" : "1", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state1_pp0_iter0_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_62", "ToInitialSV" : "0", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_76", "ToFinalSV" : "1", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state1_pp0_iter0_stage0"]},
			{"FromInitialState" : "ap_enable_state2_pp0_iter0_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_75", "FromInitialSV" : "1", "FromFinalState" : "ap_enable_state3_pp0_iter0_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_93", "FromFinalSV" : "2", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state3_pp0_iter0_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_97", "ToInitialSV" : "2", "ToFinalState" : "ap_enable_state3_pp0_iter0_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_97", "ToFinalSV" : "2", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state2_pp0_iter0_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_77", "FromInitialSV" : "1", "FromFinalState" : "ap_enable_state3_pp0_iter0_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_95", "FromFinalSV" : "2", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state3_pp0_iter0_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_99", "ToInitialSV" : "2", "ToFinalState" : "ap_enable_state3_pp0_iter0_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_99", "ToFinalSV" : "2", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state3_pp0_iter0_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_97", "FromInitialSV" : "2", "FromFinalState" : "ap_enable_state3_pp0_iter0_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_97", "FromFinalSV" : "2", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state2_pp0_iter0_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_75", "ToInitialSV" : "1", "ToFinalState" : "ap_enable_state3_pp0_iter0_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_93", "ToFinalSV" : "2", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state2_pp0_iter0_stage1"]},
			{"FromInitialState" : "ap_enable_state3_pp0_iter0_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_99", "FromInitialSV" : "2", "FromFinalState" : "ap_enable_state3_pp0_iter0_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_99", "FromFinalSV" : "2", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state2_pp0_iter0_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_77", "ToInitialSV" : "1", "ToFinalState" : "ap_enable_state3_pp0_iter0_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_95", "ToFinalSV" : "2", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state2_pp0_iter0_stage1"]},
			{"FromInitialState" : "ap_enable_state3_pp0_iter0_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_94", "FromInitialSV" : "2", "FromFinalState" : "ap_enable_state4_pp0_iter0_stage3", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_117", "FromFinalSV" : "3", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state4_pp0_iter0_stage3", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_121", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state4_pp0_iter0_stage3", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_121", "ToFinalSV" : "3", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state3_pp0_iter0_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_96", "FromInitialSV" : "2", "FromFinalState" : "ap_enable_state4_pp0_iter0_stage3", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_119", "FromFinalSV" : "3", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state4_pp0_iter0_stage3", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_123", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state4_pp0_iter0_stage3", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_123", "ToFinalSV" : "3", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state4_pp0_iter0_stage3", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_121", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state4_pp0_iter0_stage3", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_121", "FromFinalSV" : "3", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state3_pp0_iter0_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_94", "ToInitialSV" : "2", "ToFinalState" : "ap_enable_state4_pp0_iter0_stage3", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_117", "ToFinalSV" : "3", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state3_pp0_iter0_stage2"]},
			{"FromInitialState" : "ap_enable_state4_pp0_iter0_stage3", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_123", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state4_pp0_iter0_stage3", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_123", "FromFinalSV" : "3", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state3_pp0_iter0_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_96", "ToInitialSV" : "2", "ToFinalState" : "ap_enable_state4_pp0_iter0_stage3", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_119", "ToFinalSV" : "3", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state3_pp0_iter0_stage2"]},
			{"FromInitialState" : "ap_enable_state4_pp0_iter0_stage3", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_118", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state5_pp0_iter0_stage4", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_141", "FromFinalSV" : "4", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state5_pp0_iter0_stage4", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_145", "ToInitialSV" : "4", "ToFinalState" : "ap_enable_state5_pp0_iter0_stage4", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_145", "ToFinalSV" : "4", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state4_pp0_iter0_stage3", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_120", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state5_pp0_iter0_stage4", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_143", "FromFinalSV" : "4", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state5_pp0_iter0_stage4", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_147", "ToInitialSV" : "4", "ToFinalState" : "ap_enable_state5_pp0_iter0_stage4", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_147", "ToFinalSV" : "4", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state5_pp0_iter0_stage4", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_145", "FromInitialSV" : "4", "FromFinalState" : "ap_enable_state5_pp0_iter0_stage4", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_145", "FromFinalSV" : "4", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state4_pp0_iter0_stage3", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_118", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state5_pp0_iter0_stage4", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_141", "ToFinalSV" : "4", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state4_pp0_iter0_stage3"]},
			{"FromInitialState" : "ap_enable_state5_pp0_iter0_stage4", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_147", "FromInitialSV" : "4", "FromFinalState" : "ap_enable_state5_pp0_iter0_stage4", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_147", "FromFinalSV" : "4", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state4_pp0_iter0_stage3", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_120", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state5_pp0_iter0_stage4", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_143", "ToFinalSV" : "4", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state4_pp0_iter0_stage3"]},
			{"FromInitialState" : "ap_enable_state5_pp0_iter0_stage4", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_142", "FromInitialSV" : "4", "FromFinalState" : "ap_enable_state6_pp0_iter0_stage5", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_165", "FromFinalSV" : "5", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state6_pp0_iter0_stage5", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_169", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state6_pp0_iter0_stage5", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_169", "ToFinalSV" : "5", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state5_pp0_iter0_stage4", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_144", "FromInitialSV" : "4", "FromFinalState" : "ap_enable_state6_pp0_iter0_stage5", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_167", "FromFinalSV" : "5", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state6_pp0_iter0_stage5", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_171", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state6_pp0_iter0_stage5", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_171", "ToFinalSV" : "5", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state6_pp0_iter0_stage5", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_169", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state6_pp0_iter0_stage5", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_169", "FromFinalSV" : "5", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state5_pp0_iter0_stage4", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_142", "ToInitialSV" : "4", "ToFinalState" : "ap_enable_state6_pp0_iter0_stage5", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_165", "ToFinalSV" : "5", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state5_pp0_iter0_stage4"]},
			{"FromInitialState" : "ap_enable_state6_pp0_iter0_stage5", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_171", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state6_pp0_iter0_stage5", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_171", "FromFinalSV" : "5", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state5_pp0_iter0_stage4", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_144", "ToInitialSV" : "4", "ToFinalState" : "ap_enable_state6_pp0_iter0_stage5", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_167", "ToFinalSV" : "5", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state5_pp0_iter0_stage4"]},
			{"FromInitialState" : "ap_enable_state6_pp0_iter0_stage5", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_166", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state7_pp0_iter1_stage0", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_189", "FromFinalSV" : "6", "FromAddress" : "buf_val_val_V_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state7_pp0_iter1_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "null", "ToInitialOperation" : "ap_enable_operation_191", "ToInitialSV" : "6", "ToFinalState" : "ap_enable_state7_pp0_iter1_stage0", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_191", "ToFinalSV" : "6", "ToAddress" : "buf_val_val_V_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state6_pp0_iter0_stage5", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_168", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state7_pp0_iter1_stage0", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_190", "FromFinalSV" : "6", "FromAddress" : "buf_val_val_V_1_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state7_pp0_iter1_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "null", "ToInitialOperation" : "ap_enable_operation_193", "ToInitialSV" : "6", "ToFinalState" : "ap_enable_state7_pp0_iter1_stage0", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_193", "ToFinalSV" : "6", "ToAddress" : "buf_val_val_V_1_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state7_pp0_iter1_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_191", "FromInitialSV" : "6", "FromFinalState" : "ap_enable_state7_pp0_iter1_stage0", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_191", "FromFinalSV" : "6", "FromAddress" : "buf_val_val_V_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state6_pp0_iter0_stage5", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_166", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state7_pp0_iter1_stage0", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_189", "ToFinalSV" : "6", "ToAddress" : "buf_val_val_V_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state6_pp0_iter0_stage5"]},
			{"FromInitialState" : "ap_enable_state7_pp0_iter1_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_193", "FromInitialSV" : "6", "FromFinalState" : "ap_enable_state7_pp0_iter1_stage0", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_193", "FromFinalSV" : "6", "FromAddress" : "buf_val_val_V_1_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state6_pp0_iter0_stage5", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_168", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state7_pp0_iter1_stage0", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_190", "ToFinalSV" : "6", "ToAddress" : "buf_val_val_V_1_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "13", "II" : "6", "Pragma" : "(./xf_video_mem.hpp:738:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state6_pp0_iter0_stage5"]}],
		"Port" : [
			{"Name" : "out_product", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["0"], "DependentChan" : "0", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "out_product_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "tensor_y", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["0"], "DependentChan" : "0", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "tensor_y_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "TENSOR_WEIGHT_Y_OUTER_TENSOR_WEIGHT_Y_INNER", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_val_val_V_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buf_val_val_V_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U89", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U90", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U91", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U92", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U93", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U94", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U95", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U96", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U97", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U98", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U99", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U100", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U101", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U102", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U103", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U104", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U105", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_19ns_51_1_1_U106", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.flow_control_loop_pipe_U", "Parent" : "0"}]}


set ArgLastReadFirstWriteLatency {
	tensor_weight_y {
		out_product {Type I LastRead 1 FirstWrite -1}
		tensor_y {Type O LastRead -1 FirstWrite 7}}}

set hasDtUnsupportedChannel 0

set PerformanceInfo {[
	{"Name" : "Latency", "Min" : "2684931", "Max" : "2684931"}
	, {"Name" : "Interval", "Min" : "2684931", "Max" : "2684931"}
]}

set PipelineEnableSignalInfo {[
	{"Pipeline" : "0", "EnableSignal" : "ap_enable_pp0"}
]}

set Spec2ImplPortList { 
	out_product { ap_fifo {  { out_product_dout fifo_port_we 0 192 }  { out_product_num_data_valid fifo_status_num_data_valid 0 11 }  { out_product_fifo_cap fifo_update 0 11 }  { out_product_empty_n fifo_status 0 1 }  { out_product_read fifo_data 1 1 } } }
	tensor_y { ap_fifo {  { tensor_y_din fifo_port_we 1 192 }  { tensor_y_num_data_valid fifo_status_num_data_valid 0 11 }  { tensor_y_fifo_cap fifo_update 0 11 }  { tensor_y_full_n fifo_status 0 1 }  { tensor_y_write fifo_data 1 1 } } }
}
