#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("wt_i_address0", 13, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("wt_i_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("wt_i_q0", 64, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("kh_i_address0", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("kh_i_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("kh_i_q0", 64, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("dmem_i_address0", 11, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("dmem_i_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("dmem_i_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("dmem_o_address0", 7, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("dmem_o_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("dmem_o_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("dmem_o_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("n_inputs", 16, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("n_outputs", 16, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("input_words", 16, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("output_words", 16, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("layer_mode", 3, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("dmem_mode", 1, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("width_mode", 2, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("norm_mode", 2, hls_in, 11, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "top";
