-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SgdLR_dataflow_parent_loop_proc is
port (
    data_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    data_ce0 : OUT STD_LOGIC;
    data_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
    data_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    data_we0 : OUT STD_LOGIC;
    data_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    data_ce1 : OUT STD_LOGIC;
    data_d1 : OUT STD_LOGIC_VECTOR (511 downto 0);
    data_q1 : IN STD_LOGIC_VECTOR (511 downto 0);
    data_we1 : OUT STD_LOGIC;
    theta_local_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    theta_local_V_ce0 : OUT STD_LOGIC;
    theta_local_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    theta_local_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    theta_local_V_we0 : OUT STD_LOGIC;
    theta_local_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    theta_local_V_ce1 : OUT STD_LOGIC;
    theta_local_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    theta_local_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    theta_local_V_we1 : OUT STD_LOGIC;
    label_local_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    label_local_V_ce0 : OUT STD_LOGIC;
    label_local_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    label_local_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    label_local_V_we0 : OUT STD_LOGIC;
    label_local_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    label_local_V_ce1 : OUT STD_LOGIC;
    label_local_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    label_local_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    label_local_V_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of SgdLR_dataflow_parent_loop_proc is 
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv13_1194 : STD_LOGIC_VECTOR (12 downto 0) := "1000110010100";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_in_loop_TRAINING_INST_U0_data_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_data_ce0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_data_d0 : STD_LOGIC_VECTOR (511 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_data_we0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_data_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_data_ce1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_data_d1 : STD_LOGIC_VECTOR (511 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_data_we1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_we0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_theta_local_V_we1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_ce0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_we0 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_ce1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_TRAINING_INST_U0_label_local_V_we1 : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_TRAINING_INST_U0_ap_continue : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component SgdLR_dataflow_in_loop_TRAINING_INST IS
    port (
        trunc_ln280 : IN STD_LOGIC_VECTOR (12 downto 0);
        data_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        data_ce0 : OUT STD_LOGIC;
        data_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
        data_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        data_we0 : OUT STD_LOGIC;
        data_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        data_ce1 : OUT STD_LOGIC;
        data_d1 : OUT STD_LOGIC_VECTOR (511 downto 0);
        data_q1 : IN STD_LOGIC_VECTOR (511 downto 0);
        data_we1 : OUT STD_LOGIC;
        theta_local_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        theta_local_V_ce0 : OUT STD_LOGIC;
        theta_local_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        theta_local_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        theta_local_V_we0 : OUT STD_LOGIC;
        theta_local_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        theta_local_V_ce1 : OUT STD_LOGIC;
        theta_local_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        theta_local_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        theta_local_V_we1 : OUT STD_LOGIC;
        label_local_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        label_local_V_ce0 : OUT STD_LOGIC;
        label_local_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        label_local_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        label_local_V_we0 : OUT STD_LOGIC;
        label_local_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        label_local_V_ce1 : OUT STD_LOGIC;
        label_local_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        label_local_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        label_local_V_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        trunc_ln280_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_TRAINING_INST_U0 : component SgdLR_dataflow_in_loop_TRAINING_INST
    port map (
        trunc_ln280 => loop_dataflow_input_count,
        data_address0 => dataflow_in_loop_TRAINING_INST_U0_data_address0,
        data_ce0 => dataflow_in_loop_TRAINING_INST_U0_data_ce0,
        data_d0 => dataflow_in_loop_TRAINING_INST_U0_data_d0,
        data_q0 => data_q0,
        data_we0 => dataflow_in_loop_TRAINING_INST_U0_data_we0,
        data_address1 => dataflow_in_loop_TRAINING_INST_U0_data_address1,
        data_ce1 => dataflow_in_loop_TRAINING_INST_U0_data_ce1,
        data_d1 => dataflow_in_loop_TRAINING_INST_U0_data_d1,
        data_q1 => ap_const_lv512_lc_1,
        data_we1 => dataflow_in_loop_TRAINING_INST_U0_data_we1,
        theta_local_V_address0 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address0,
        theta_local_V_ce0 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce0,
        theta_local_V_d0 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_d0,
        theta_local_V_q0 => theta_local_V_q0,
        theta_local_V_we0 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_we0,
        theta_local_V_address1 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address1,
        theta_local_V_ce1 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce1,
        theta_local_V_d1 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_d1,
        theta_local_V_q1 => theta_local_V_q1,
        theta_local_V_we1 => dataflow_in_loop_TRAINING_INST_U0_theta_local_V_we1,
        label_local_V_address0 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_address0,
        label_local_V_ce0 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_ce0,
        label_local_V_d0 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_d0,
        label_local_V_q0 => label_local_V_q0,
        label_local_V_we0 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_we0,
        label_local_V_address1 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_address1,
        label_local_V_ce1 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_ce1,
        label_local_V_d1 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_d1,
        label_local_V_q1 => ap_const_lv8_0,
        label_local_V_we1 => dataflow_in_loop_TRAINING_INST_U0_label_local_V_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        trunc_ln280_ap_vld => ap_const_logic_0,
        ap_start => dataflow_in_loop_TRAINING_INST_U0_ap_start,
        ap_done => dataflow_in_loop_TRAINING_INST_U0_ap_done,
        ap_ready => dataflow_in_loop_TRAINING_INST_U0_ap_ready,
        ap_idle => dataflow_in_loop_TRAINING_INST_U0_ap_idle,
        ap_continue => dataflow_in_loop_TRAINING_INST_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv13_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TRAINING_INST_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv13_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TRAINING_INST_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv13_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv13_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_in_loop_TRAINING_INST_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_TRAINING_INST_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv13_1));
                elsif (((dataflow_in_loop_TRAINING_INST_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_TRAINING_INST_U0_ap_done = ap_const_logic_1) and (loop_dataflow_output_count = bound_minus_1))) then 
                    loop_dataflow_output_count <= ap_const_lv13_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_TRAINING_INST_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((dataflow_in_loop_TRAINING_INST_U0_ap_done = ap_const_logic_1) and (loop_dataflow_output_count = bound_minus_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_in_loop_TRAINING_INST_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((ap_start = ap_const_logic_0) and (dataflow_in_loop_TRAINING_INST_U0_ap_idle = ap_const_logic_1) and (loop_dataflow_output_count = ap_const_lv13_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(dataflow_in_loop_TRAINING_INST_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TRAINING_INST_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_minus_1 <= std_logic_vector(unsigned(ap_const_lv13_1194) - unsigned(ap_const_lv13_1));
    data_address0 <= dataflow_in_loop_TRAINING_INST_U0_data_address0;
    data_address1 <= ap_const_lv18_0;
    data_ce0 <= dataflow_in_loop_TRAINING_INST_U0_data_ce0;
    data_ce1 <= ap_const_logic_0;
    data_d0 <= ap_const_lv512_lc_1;
    data_d1 <= ap_const_lv512_lc_1;
    data_we0 <= ap_const_logic_0;
    data_we1 <= ap_const_logic_0;

    dataflow_in_loop_TRAINING_INST_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_TRAINING_INST_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_TRAINING_INST_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_TRAINING_INST_U0_ap_start <= ap_start;
    label_local_V_address0 <= dataflow_in_loop_TRAINING_INST_U0_label_local_V_address0;
    label_local_V_address1 <= ap_const_lv13_0;
    label_local_V_ce0 <= dataflow_in_loop_TRAINING_INST_U0_label_local_V_ce0;
    label_local_V_ce1 <= ap_const_logic_0;
    label_local_V_d0 <= ap_const_lv8_0;
    label_local_V_d1 <= ap_const_lv8_0;
    label_local_V_we0 <= ap_const_logic_0;
    label_local_V_we1 <= ap_const_logic_0;
    theta_local_V_address0 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address0;
    theta_local_V_address1 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_address1;
    theta_local_V_ce0 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce0;
    theta_local_V_ce1 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_ce1;
    theta_local_V_d0 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_d0;
    theta_local_V_d1 <= ap_const_lv32_0;
    theta_local_V_we0 <= dataflow_in_loop_TRAINING_INST_U0_theta_local_V_we0;
    theta_local_V_we1 <= ap_const_logic_0;
end behav;
