-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_bin_dense_Pipeline_LOOP_DENSE_I is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    n_inputs : IN STD_LOGIC_VECTOR (15 downto 0);
    phi_mul : IN STD_LOGIC_VECTOR (19 downto 0);
    d_i_idx : IN STD_LOGIC_VECTOR (0 downto 0);
    sum_V_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    sum_V_out_ap_vld : OUT STD_LOGIC;
    dmem_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    dmem_V_ce0 : OUT STD_LOGIC;
    dmem_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    dmem_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    dmem_V_ce1 : OUT STD_LOGIC;
    dmem_V_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    wt_mem_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    wt_mem_V_ce0 : OUT STD_LOGIC;
    wt_mem_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    wt_mem_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    wt_mem_V_ce1 : OUT STD_LOGIC;
    wt_mem_V_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of top_bin_dense_Pipeline_LOOP_DENSE_I is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv12_400 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_const_lv13_925 : STD_LOGIC_VECTOR (12 downto 0) := "0100100100101";
    constant ap_const_lv16_80 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_40 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1027_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln1027_reg_3710 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_3734 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_reg_3739 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_reg_3745 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_reg_3751 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_reg_3758 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_reg_3765 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_reg_3772 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_reg_3779 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_reg_3787 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_reg_3795 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_reg_3803 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_reg_3811 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_reg_3819 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_reg_3827 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_reg_3835 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1497_fu_971_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1497_reg_3843 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_3852 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_3857 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_reg_3863 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_reg_3869 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_reg_3876 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_reg_3883 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_reg_3890 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_reg_3897 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_reg_3905 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_26_reg_3913 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_27_reg_3921 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_28_reg_3929 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_reg_3937 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_reg_3945 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_reg_3953 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_reg_3961 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_50_reg_3970 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_51_reg_3975 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_52_reg_3981 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_53_reg_3987 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_71_reg_3994 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_72_reg_4001 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_73_reg_4008 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_74_reg_4015 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_75_reg_4023 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_76_reg_4031 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_77_reg_4039 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_78_reg_4047 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_79_reg_4055 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_80_reg_4063 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_81_reg_4071 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1497_1_fu_1687_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1497_1_reg_4079 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_82_reg_4088 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_83_reg_4093 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_84_reg_4099 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_85_reg_4105 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_87_reg_4112 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_88_reg_4119 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_89_reg_4126 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_90_reg_4133 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_91_reg_4141 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_92_reg_4149 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_93_reg_4157 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_94_reg_4165 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_95_reg_4173 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_96_reg_4181 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_97_reg_4189 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_98_reg_4197 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln624_fu_376_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln624_1_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv_i749_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln625_fu_403_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_V_fu_234 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln840_27_fu_3680_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal rhs_V_fu_238 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_V_fu_408_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_i_V_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1495_fu_336_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal ret_V_fu_340_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_s_fu_356_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_366_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln624_fu_381_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_s_fu_346_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln625_fu_397_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln1499_fu_419_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_425_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_433_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_441_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_449_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_457_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_465_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_473_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_481_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_fu_489_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_497_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_fu_505_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_64_fu_513_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_65_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_529_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_67_fu_537_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_68_fu_545_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_69_fu_553_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_fu_561_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_fu_569_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_109_fu_577_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_121_fu_585_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_122_fu_593_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_123_fu_601_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_124_fu_609_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_125_fu_617_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_126_fu_625_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_127_fu_633_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_128_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_129_fu_649_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_130_fu_657_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_131_fu_665_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_132_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln_fu_681_p64 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln841_fu_811_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln841_fu_815_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln1499_1_fu_1135_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_134_fu_1141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_135_fu_1149_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_136_fu_1157_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_137_fu_1165_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_138_fu_1173_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_fu_1181_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_fu_1189_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_141_fu_1197_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_142_fu_1205_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_fu_1213_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_144_fu_1221_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_145_fu_1229_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_146_fu_1237_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_fu_1245_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_fu_1253_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_149_fu_1261_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_150_fu_1269_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_151_fu_1277_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_152_fu_1285_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_153_fu_1293_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_169_fu_1301_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_192_fu_1309_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_204_fu_1317_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_205_fu_1325_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_206_fu_1333_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_207_fu_1341_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_208_fu_1349_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_209_fu_1357_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_210_fu_1365_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_211_fu_1373_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_212_fu_1381_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_213_fu_1389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1497_1_fu_1397_p64 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln841_1_fu_1527_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln841_1_fu_1531_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln1497_9_fu_1854_p32 : STD_LOGIC_VECTOR (61 downto 0);
    signal and_ln1497_s_fu_1957_p32 : STD_LOGIC_VECTOR (61 downto 0);
    signal and_ln1497_9_cast_fu_1904_p31 : STD_LOGIC_VECTOR (58 downto 0);
    signal and_ln1497_cast_fu_2007_p31 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln631_fu_2056_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln1669_fu_1953_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln1669_2_fu_2080_p27 : STD_LOGIC_VECTOR (50 downto 0);
    signal trunc_ln1669_3_fu_2127_p27 : STD_LOGIC_VECTOR (50 downto 0);
    signal zext_ln631_3_fu_2064_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal zext_ln631_2_fu_2060_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln631_fu_2074_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln632_2_fu_2180_p4 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln632_3_fu_2200_p19 : STD_LOGIC_VECTOR (34 downto 0);
    signal trunc_ln632_4_fu_2235_p19 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln1669_3_fu_2170_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln1669_2_fu_2123_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal add_ln631_2_fu_2068_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln632_fu_2190_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln1669_fu_2174_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal zext_ln632_7_fu_2266_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln632_6_fu_2231_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal trunc_ln632_5_cast_fu_2276_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal add_ln632_2_fu_2270_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln632_6_cast_fu_2308_p4 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln632_3_fu_2302_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln632_4_fu_2318_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_33_fu_2330_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_34_fu_2340_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_35_fu_2350_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_36_fu_2360_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_37_fu_2370_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_38_fu_2380_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1669_fu_2390_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln1_fu_2394_p15 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln632_fu_2286_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_39_fu_2430_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_40_fu_2440_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_41_fu_2450_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_42_fu_2460_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_43_fu_2470_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_44_fu_2480_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_45_fu_2490_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln840_4_fu_2500_p14 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln632_1_fu_2194_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln_fu_2292_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln840_19_fu_2534_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln632_2_fu_2197_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1669_2_fu_2324_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_46_fu_2546_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_47_fu_2556_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_48_fu_2566_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_49_fu_2576_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln840_fu_2586_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln2_fu_2590_p11 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln840_5_fu_2618_p11 : STD_LOGIC_VECTOR (36 downto 0);
    signal zext_ln840_fu_2530_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln1669_4_fu_2426_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln840_2_fu_2642_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal zext_ln840_1_fu_2614_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln1669_4_fu_2652_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln840_20_fu_2646_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_133_fu_2662_p4 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln840_fu_2540_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1_fu_2680_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln840_4_fu_2672_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln840_3_fu_2658_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln840_21_fu_2692_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln840_6_fu_2688_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln840_5_fu_2676_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln1669_5_fu_2718_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln840_1_fu_2698_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln2_fu_2708_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln1669_6_fu_2728_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1669_5_fu_2724_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln1669_1_fu_2734_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_2740_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln638_fu_2748_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln638_fu_2752_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal and_ln1497_2_fu_2762_p32 : STD_LOGIC_VECTOR (61 downto 0);
    signal and_ln1497_3_fu_2865_p32 : STD_LOGIC_VECTOR (61 downto 0);
    signal and_ln1497_2_cast_fu_2812_p31 : STD_LOGIC_VECTOR (58 downto 0);
    signal and_ln1497_3_cast_fu_2915_p31 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln631_1_fu_2964_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln1669_1_fu_2861_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln1669_4_fu_2988_p27 : STD_LOGIC_VECTOR (50 downto 0);
    signal trunc_ln1669_5_fu_3035_p27 : STD_LOGIC_VECTOR (50 downto 0);
    signal zext_ln631_5_fu_2972_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal zext_ln631_4_fu_2968_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln631_1_fu_2982_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln632_7_fu_3088_p4 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln632_8_fu_3108_p19 : STD_LOGIC_VECTOR (34 downto 0);
    signal trunc_ln632_9_fu_3143_p19 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln1669_7_fu_3078_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln1669_6_fu_3031_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal add_ln631_3_fu_2976_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln632_3_fu_3098_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln1669_7_fu_3082_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal zext_ln632_9_fu_3174_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln632_8_fu_3139_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal trunc_ln632_cast_fu_3184_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal add_ln632_5_fu_3178_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln632_10_cast_fu_3216_p4 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln632_6_fu_3210_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln632_7_fu_3226_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_99_fu_3238_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_100_fu_3248_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_101_fu_3258_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_102_fu_3268_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_103_fu_3278_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_104_fu_3288_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1669_6_fu_3298_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln1669_2_fu_3302_p15 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln632_1_fu_3194_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_105_fu_3338_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_106_fu_3348_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_107_fu_3358_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_108_fu_3368_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_110_fu_3378_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_111_fu_3388_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_112_fu_3398_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln840_7_fu_3408_p14 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln632_4_fu_3102_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln632_1_fu_3200_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln840_22_fu_3442_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln632_5_fu_3105_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1669_8_fu_3232_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_113_fu_3454_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_114_fu_3464_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_115_fu_3474_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_116_fu_3484_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln840_6_fu_3494_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln840_1_fu_3498_p11 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln840_8_fu_3526_p11 : STD_LOGIC_VECTOR (36 downto 0);
    signal zext_ln840_7_fu_3438_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln1669_8_fu_3334_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln840_9_fu_3550_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal zext_ln840_8_fu_3522_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln1669_9_fu_3560_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln840_24_fu_3554_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_214_fu_3570_p4 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln840_23_fu_3448_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln840_2_fu_3588_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln840_11_fu_3580_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln840_10_fu_3566_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln840_25_fu_3600_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln840_13_fu_3596_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln840_12_fu_3584_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln1669_10_fu_3626_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln1669_9_fu_3632_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln840_3_fu_3606_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln1669_11_fu_3636_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln1669_1_fu_3616_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln1669_3_fu_3642_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1669_1_fu_3648_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln638_1_fu_3656_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln638_1_fu_3660_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln840_fu_3666_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln624_fu_2758_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln840_26_fu_3670_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln840_7_fu_3676_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    rhs_V_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1027_fu_330_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    rhs_V_fu_238 <= i_V_fu_408_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    rhs_V_fu_238 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    sum_V_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_V_fu_234 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    sum_V_fu_234 <= add_ln840_27_fu_3680_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln1027_reg_3710 <= icmp_ln1027_fu_330_p2;
                tmp_10_reg_3787 <= sub_ln841_fu_815_p2(29 downto 28);
                tmp_11_reg_3795 <= sub_ln841_fu_815_p2(25 downto 24);
                tmp_12_reg_3803 <= sub_ln841_fu_815_p2(21 downto 20);
                tmp_13_reg_3811 <= sub_ln841_fu_815_p2(17 downto 16);
                tmp_14_reg_3819 <= sub_ln841_fu_815_p2(13 downto 12);
                tmp_15_reg_3827 <= sub_ln841_fu_815_p2(9 downto 8);
                tmp_16_reg_3835 <= sub_ln841_fu_815_p2(5 downto 4);
                tmp_17_reg_3852 <= sub_ln841_fu_815_p2(63 downto 62);
                tmp_18_reg_3857 <= sub_ln841_fu_815_p2(59 downto 58);
                tmp_19_reg_3863 <= sub_ln841_fu_815_p2(55 downto 54);
                tmp_20_reg_3869 <= sub_ln841_fu_815_p2(51 downto 50);
                tmp_21_reg_3876 <= sub_ln841_fu_815_p2(47 downto 46);
                tmp_22_reg_3883 <= sub_ln841_fu_815_p2(43 downto 42);
                tmp_23_reg_3890 <= sub_ln841_fu_815_p2(39 downto 38);
                tmp_24_reg_3897 <= sub_ln841_fu_815_p2(35 downto 34);
                tmp_25_reg_3905 <= sub_ln841_fu_815_p2(31 downto 30);
                tmp_26_reg_3913 <= sub_ln841_fu_815_p2(27 downto 26);
                tmp_27_reg_3921 <= sub_ln841_fu_815_p2(23 downto 22);
                tmp_28_reg_3929 <= sub_ln841_fu_815_p2(19 downto 18);
                tmp_29_reg_3937 <= sub_ln841_fu_815_p2(15 downto 14);
                tmp_2_reg_3734 <= sub_ln841_fu_815_p2(61 downto 60);
                tmp_30_reg_3945 <= sub_ln841_fu_815_p2(11 downto 10);
                tmp_31_reg_3953 <= sub_ln841_fu_815_p2(7 downto 6);
                tmp_32_reg_3961 <= sub_ln841_fu_815_p2(3 downto 2);
                tmp_3_reg_3739 <= sub_ln841_fu_815_p2(57 downto 56);
                tmp_4_reg_3745 <= sub_ln841_fu_815_p2(53 downto 52);
                tmp_50_reg_3970 <= sub_ln841_1_fu_1531_p2(61 downto 60);
                tmp_51_reg_3975 <= sub_ln841_1_fu_1531_p2(57 downto 56);
                tmp_52_reg_3981 <= sub_ln841_1_fu_1531_p2(53 downto 52);
                tmp_53_reg_3987 <= sub_ln841_1_fu_1531_p2(49 downto 48);
                tmp_5_reg_3751 <= sub_ln841_fu_815_p2(49 downto 48);
                tmp_6_reg_3758 <= sub_ln841_fu_815_p2(45 downto 44);
                tmp_71_reg_3994 <= sub_ln841_1_fu_1531_p2(45 downto 44);
                tmp_72_reg_4001 <= sub_ln841_1_fu_1531_p2(41 downto 40);
                tmp_73_reg_4008 <= sub_ln841_1_fu_1531_p2(37 downto 36);
                tmp_74_reg_4015 <= sub_ln841_1_fu_1531_p2(33 downto 32);
                tmp_75_reg_4023 <= sub_ln841_1_fu_1531_p2(29 downto 28);
                tmp_76_reg_4031 <= sub_ln841_1_fu_1531_p2(25 downto 24);
                tmp_77_reg_4039 <= sub_ln841_1_fu_1531_p2(21 downto 20);
                tmp_78_reg_4047 <= sub_ln841_1_fu_1531_p2(17 downto 16);
                tmp_79_reg_4055 <= sub_ln841_1_fu_1531_p2(13 downto 12);
                tmp_7_reg_3765 <= sub_ln841_fu_815_p2(41 downto 40);
                tmp_80_reg_4063 <= sub_ln841_1_fu_1531_p2(9 downto 8);
                tmp_81_reg_4071 <= sub_ln841_1_fu_1531_p2(5 downto 4);
                tmp_82_reg_4088 <= sub_ln841_1_fu_1531_p2(63 downto 62);
                tmp_83_reg_4093 <= sub_ln841_1_fu_1531_p2(59 downto 58);
                tmp_84_reg_4099 <= sub_ln841_1_fu_1531_p2(55 downto 54);
                tmp_85_reg_4105 <= sub_ln841_1_fu_1531_p2(51 downto 50);
                tmp_87_reg_4112 <= sub_ln841_1_fu_1531_p2(47 downto 46);
                tmp_88_reg_4119 <= sub_ln841_1_fu_1531_p2(43 downto 42);
                tmp_89_reg_4126 <= sub_ln841_1_fu_1531_p2(39 downto 38);
                tmp_8_reg_3772 <= sub_ln841_fu_815_p2(37 downto 36);
                tmp_90_reg_4133 <= sub_ln841_1_fu_1531_p2(35 downto 34);
                tmp_91_reg_4141 <= sub_ln841_1_fu_1531_p2(31 downto 30);
                tmp_92_reg_4149 <= sub_ln841_1_fu_1531_p2(27 downto 26);
                tmp_93_reg_4157 <= sub_ln841_1_fu_1531_p2(23 downto 22);
                tmp_94_reg_4165 <= sub_ln841_1_fu_1531_p2(19 downto 18);
                tmp_95_reg_4173 <= sub_ln841_1_fu_1531_p2(15 downto 14);
                tmp_96_reg_4181 <= sub_ln841_1_fu_1531_p2(11 downto 10);
                tmp_97_reg_4189 <= sub_ln841_1_fu_1531_p2(7 downto 6);
                tmp_98_reg_4197 <= sub_ln841_1_fu_1531_p2(3 downto 2);
                tmp_9_reg_3779 <= sub_ln841_fu_815_p2(33 downto 32);
                trunc_ln1497_1_reg_4079 <= trunc_ln1497_1_fu_1687_p1;
                trunc_ln1497_reg_3843 <= trunc_ln1497_fu_971_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1669_10_fu_3626_p2 <= std_logic_vector(unsigned(zext_ln840_13_fu_3596_p1) + unsigned(zext_ln840_12_fu_3584_p1));
    add_ln1669_11_fu_3636_p2 <= std_logic_vector(unsigned(zext_ln1669_9_fu_3632_p1) + unsigned(trunc_ln840_3_fu_3606_p4));
    add_ln1669_1_fu_2734_p2 <= std_logic_vector(unsigned(add_ln1669_6_fu_2728_p2) + unsigned(zext_ln1669_5_fu_2724_p1));
    add_ln1669_2_fu_2324_p2 <= std_logic_vector(unsigned(trunc_ln632_6_cast_fu_2308_p4) + unsigned(add_ln632_3_fu_2302_p2));
    add_ln1669_3_fu_3642_p2 <= std_logic_vector(unsigned(add_ln1669_11_fu_3636_p2) + unsigned(trunc_ln1669_1_fu_3616_p4));
    add_ln1669_4_fu_2652_p2 <= std_logic_vector(unsigned(zext_ln840_2_fu_2642_p1) + unsigned(zext_ln840_1_fu_2614_p1));
    add_ln1669_5_fu_2718_p2 <= std_logic_vector(unsigned(zext_ln840_6_fu_2688_p1) + unsigned(zext_ln840_5_fu_2676_p1));
    add_ln1669_6_fu_2728_p2 <= std_logic_vector(unsigned(trunc_ln840_1_fu_2698_p4) + unsigned(trunc_ln2_fu_2708_p4));
    add_ln1669_7_fu_3082_p2 <= std_logic_vector(unsigned(zext_ln631_5_fu_2972_p1) + unsigned(zext_ln631_4_fu_2968_p1));
    add_ln1669_8_fu_3232_p2 <= std_logic_vector(unsigned(trunc_ln632_10_cast_fu_3216_p4) + unsigned(add_ln632_6_fu_3210_p2));
    add_ln1669_9_fu_3560_p2 <= std_logic_vector(unsigned(zext_ln840_9_fu_3550_p1) + unsigned(zext_ln840_8_fu_3522_p1));
    add_ln1669_fu_2174_p2 <= std_logic_vector(unsigned(zext_ln631_3_fu_2064_p1) + unsigned(zext_ln631_2_fu_2060_p1));
    add_ln625_fu_397_p2 <= std_logic_vector(unsigned(ret_V_s_fu_346_p4) + unsigned(ap_const_lv13_925));
    add_ln631_1_fu_2982_p2 <= std_logic_vector(unsigned(zext_ln631_1_fu_2964_p1) + unsigned(zext_ln1669_1_fu_2861_p1));
    add_ln631_2_fu_2068_p2 <= std_logic_vector(unsigned(and_ln1497_cast_fu_2007_p31) + unsigned(and_ln1497_9_cast_fu_1904_p31));
    add_ln631_3_fu_2976_p2 <= std_logic_vector(unsigned(and_ln1497_3_cast_fu_2915_p31) + unsigned(and_ln1497_2_cast_fu_2812_p31));
    add_ln631_fu_2074_p2 <= std_logic_vector(unsigned(zext_ln631_fu_2056_p1) + unsigned(zext_ln1669_fu_1953_p1));
    add_ln632_1_fu_3194_p2 <= std_logic_vector(unsigned(zext_ln632_3_fu_3098_p1) + unsigned(add_ln1669_7_fu_3082_p2));
    add_ln632_2_fu_2270_p2 <= std_logic_vector(unsigned(zext_ln1669_3_fu_2170_p1) + unsigned(zext_ln1669_2_fu_2123_p1));
    add_ln632_3_fu_2302_p2 <= std_logic_vector(unsigned(zext_ln632_7_fu_2266_p1) + unsigned(zext_ln632_6_fu_2231_p1));
    add_ln632_4_fu_2318_p2 <= std_logic_vector(unsigned(trunc_ln632_5_cast_fu_2276_p4) + unsigned(add_ln632_2_fu_2270_p2));
    add_ln632_5_fu_3178_p2 <= std_logic_vector(unsigned(zext_ln1669_7_fu_3078_p1) + unsigned(zext_ln1669_6_fu_3031_p1));
    add_ln632_6_fu_3210_p2 <= std_logic_vector(unsigned(zext_ln632_9_fu_3174_p1) + unsigned(zext_ln632_8_fu_3139_p1));
    add_ln632_7_fu_3226_p2 <= std_logic_vector(unsigned(trunc_ln632_cast_fu_3184_p4) + unsigned(add_ln632_5_fu_3178_p2));
    add_ln632_fu_2286_p2 <= std_logic_vector(unsigned(zext_ln632_fu_2190_p1) + unsigned(add_ln1669_fu_2174_p2));
    add_ln840_19_fu_2534_p2 <= std_logic_vector(unsigned(zext_ln632_1_fu_2194_p1) + unsigned(trunc_ln_fu_2292_p4));
    add_ln840_20_fu_2646_p2 <= std_logic_vector(unsigned(zext_ln840_fu_2530_p1) + unsigned(zext_ln1669_4_fu_2426_p1));
    add_ln840_21_fu_2692_p2 <= std_logic_vector(unsigned(zext_ln840_4_fu_2672_p1) + unsigned(zext_ln840_3_fu_2658_p1));
    add_ln840_22_fu_3442_p2 <= std_logic_vector(unsigned(zext_ln632_4_fu_3102_p1) + unsigned(trunc_ln632_1_fu_3200_p4));
    add_ln840_23_fu_3448_p2 <= std_logic_vector(unsigned(add_ln840_22_fu_3442_p2) + unsigned(zext_ln632_5_fu_3105_p1));
    add_ln840_24_fu_3554_p2 <= std_logic_vector(unsigned(zext_ln840_7_fu_3438_p1) + unsigned(zext_ln1669_8_fu_3334_p1));
    add_ln840_25_fu_3600_p2 <= std_logic_vector(unsigned(zext_ln840_11_fu_3580_p1) + unsigned(zext_ln840_10_fu_3566_p1));
    add_ln840_26_fu_3670_p2 <= std_logic_vector(signed(sext_ln840_fu_3666_p1) + signed(sext_ln624_fu_2758_p1));
    add_ln840_27_fu_3680_p2 <= std_logic_vector(unsigned(sum_V_fu_234) + unsigned(sext_ln840_7_fu_3676_p1));
    add_ln840_fu_2540_p2 <= std_logic_vector(unsigned(add_ln840_19_fu_2534_p2) + unsigned(zext_ln632_2_fu_2197_p1));
    and_ln1497_1_fu_1397_p64 <= ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((tmp_134_fu_1141_p3 & ap_const_lv1_0) & tmp_135_fu_1149_p3) & ap_const_lv1_0) & tmp_136_fu_1157_p3) & ap_const_lv1_0) & tmp_137_fu_1165_p3) & ap_const_lv1_0) & tmp_138_fu_1173_p3) & ap_const_lv1_0) & tmp_139_fu_1181_p3) & ap_const_lv1_0) & tmp_140_fu_1189_p3) & ap_const_lv1_0) & tmp_141_fu_1197_p3) & ap_const_lv1_0) & tmp_142_fu_1205_p3) & ap_const_lv1_0) & tmp_143_fu_1213_p3) & ap_const_lv1_0) & tmp_144_fu_1221_p3) & ap_const_lv1_0) & tmp_145_fu_1229_p3) & ap_const_lv1_0) & tmp_146_fu_1237_p3) & ap_const_lv1_0) & tmp_147_fu_1245_p3) & ap_const_lv1_0) & tmp_148_fu_1253_p3) & ap_const_lv1_0) & tmp_149_fu_1261_p3) & ap_const_lv1_0) & tmp_150_fu_1269_p3) & ap_const_lv1_0) & tmp_151_fu_1277_p3) & ap_const_lv1_0) & tmp_152_fu_1285_p3) & ap_const_lv1_0) & tmp_153_fu_1293_p3) & ap_const_lv1_0) & tmp_169_fu_1301_p3) & ap_const_lv1_0) & tmp_192_fu_1309_p3) & ap_const_lv1_0) & tmp_204_fu_1317_p3) & ap_const_lv1_0) & tmp_205_fu_1325_p3) & ap_const_lv1_0) & tmp_206_fu_1333_p3) & ap_const_lv1_0) & tmp_207_fu_1341_p3) & ap_const_lv1_0) & tmp_208_fu_1349_p3) & ap_const_lv1_0) & tmp_209_fu_1357_p3) & ap_const_lv1_0) & tmp_210_fu_1365_p3) & ap_const_lv1_0) & tmp_211_fu_1373_p3) & ap_const_lv1_0) & tmp_212_fu_1381_p3) & ap_const_lv1_0) & tmp_213_fu_1389_p3);
    and_ln1497_2_cast_fu_2812_p31 <= (((((((((((((((((((((((((((((ap_const_lv1_0 & tmp_51_reg_3975) & ap_const_lv2_0) & tmp_52_reg_3981) & ap_const_lv2_0) & tmp_53_reg_3987) & ap_const_lv2_0) & tmp_71_reg_3994) & ap_const_lv2_0) & tmp_72_reg_4001) & ap_const_lv2_0) & tmp_73_reg_4008) & ap_const_lv2_0) & tmp_74_reg_4015) & ap_const_lv2_0) & tmp_75_reg_4023) & ap_const_lv2_0) & tmp_76_reg_4031) & ap_const_lv2_0) & tmp_77_reg_4039) & ap_const_lv2_0) & tmp_78_reg_4047) & ap_const_lv2_0) & tmp_79_reg_4055) & ap_const_lv2_0) & tmp_80_reg_4063) & ap_const_lv2_0) & tmp_81_reg_4071) & ap_const_lv2_0) & trunc_ln1497_1_reg_4079);
    and_ln1497_2_fu_2762_p32 <= ((((((((((((((((((((((((((((((tmp_50_reg_3970 & ap_const_lv2_0) & tmp_51_reg_3975) & ap_const_lv2_0) & tmp_52_reg_3981) & ap_const_lv2_0) & tmp_53_reg_3987) & ap_const_lv2_0) & tmp_71_reg_3994) & ap_const_lv2_0) & tmp_72_reg_4001) & ap_const_lv2_0) & tmp_73_reg_4008) & ap_const_lv2_0) & tmp_74_reg_4015) & ap_const_lv2_0) & tmp_75_reg_4023) & ap_const_lv2_0) & tmp_76_reg_4031) & ap_const_lv2_0) & tmp_77_reg_4039) & ap_const_lv2_0) & tmp_78_reg_4047) & ap_const_lv2_0) & tmp_79_reg_4055) & ap_const_lv2_0) & tmp_80_reg_4063) & ap_const_lv2_0) & tmp_81_reg_4071) & ap_const_lv2_0) & trunc_ln1497_1_reg_4079);
    and_ln1497_3_cast_fu_2915_p31 <= (((((((((((((((((((((((((((((ap_const_lv1_0 & tmp_83_reg_4093) & ap_const_lv2_0) & tmp_84_reg_4099) & ap_const_lv2_0) & tmp_85_reg_4105) & ap_const_lv2_0) & tmp_87_reg_4112) & ap_const_lv2_0) & tmp_88_reg_4119) & ap_const_lv2_0) & tmp_89_reg_4126) & ap_const_lv2_0) & tmp_90_reg_4133) & ap_const_lv2_0) & tmp_91_reg_4141) & ap_const_lv2_0) & tmp_92_reg_4149) & ap_const_lv2_0) & tmp_93_reg_4157) & ap_const_lv2_0) & tmp_94_reg_4165) & ap_const_lv2_0) & tmp_95_reg_4173) & ap_const_lv2_0) & tmp_96_reg_4181) & ap_const_lv2_0) & tmp_97_reg_4189) & ap_const_lv2_0) & tmp_98_reg_4197);
    and_ln1497_3_fu_2865_p32 <= ((((((((((((((((((((((((((((((tmp_82_reg_4088 & ap_const_lv2_0) & tmp_83_reg_4093) & ap_const_lv2_0) & tmp_84_reg_4099) & ap_const_lv2_0) & tmp_85_reg_4105) & ap_const_lv2_0) & tmp_87_reg_4112) & ap_const_lv2_0) & tmp_88_reg_4119) & ap_const_lv2_0) & tmp_89_reg_4126) & ap_const_lv2_0) & tmp_90_reg_4133) & ap_const_lv2_0) & tmp_91_reg_4141) & ap_const_lv2_0) & tmp_92_reg_4149) & ap_const_lv2_0) & tmp_93_reg_4157) & ap_const_lv2_0) & tmp_94_reg_4165) & ap_const_lv2_0) & tmp_95_reg_4173) & ap_const_lv2_0) & tmp_96_reg_4181) & ap_const_lv2_0) & tmp_97_reg_4189) & ap_const_lv2_0) & tmp_98_reg_4197);
    and_ln1497_9_cast_fu_1904_p31 <= (((((((((((((((((((((((((((((ap_const_lv1_0 & tmp_3_reg_3739) & ap_const_lv2_0) & tmp_4_reg_3745) & ap_const_lv2_0) & tmp_5_reg_3751) & ap_const_lv2_0) & tmp_6_reg_3758) & ap_const_lv2_0) & tmp_7_reg_3765) & ap_const_lv2_0) & tmp_8_reg_3772) & ap_const_lv2_0) & tmp_9_reg_3779) & ap_const_lv2_0) & tmp_10_reg_3787) & ap_const_lv2_0) & tmp_11_reg_3795) & ap_const_lv2_0) & tmp_12_reg_3803) & ap_const_lv2_0) & tmp_13_reg_3811) & ap_const_lv2_0) & tmp_14_reg_3819) & ap_const_lv2_0) & tmp_15_reg_3827) & ap_const_lv2_0) & tmp_16_reg_3835) & ap_const_lv2_0) & trunc_ln1497_reg_3843);
    and_ln1497_9_fu_1854_p32 <= ((((((((((((((((((((((((((((((tmp_2_reg_3734 & ap_const_lv2_0) & tmp_3_reg_3739) & ap_const_lv2_0) & tmp_4_reg_3745) & ap_const_lv2_0) & tmp_5_reg_3751) & ap_const_lv2_0) & tmp_6_reg_3758) & ap_const_lv2_0) & tmp_7_reg_3765) & ap_const_lv2_0) & tmp_8_reg_3772) & ap_const_lv2_0) & tmp_9_reg_3779) & ap_const_lv2_0) & tmp_10_reg_3787) & ap_const_lv2_0) & tmp_11_reg_3795) & ap_const_lv2_0) & tmp_12_reg_3803) & ap_const_lv2_0) & tmp_13_reg_3811) & ap_const_lv2_0) & tmp_14_reg_3819) & ap_const_lv2_0) & tmp_15_reg_3827) & ap_const_lv2_0) & tmp_16_reg_3835) & ap_const_lv2_0) & trunc_ln1497_reg_3843);
    and_ln1497_cast_fu_2007_p31 <= (((((((((((((((((((((((((((((ap_const_lv1_0 & tmp_18_reg_3857) & ap_const_lv2_0) & tmp_19_reg_3863) & ap_const_lv2_0) & tmp_20_reg_3869) & ap_const_lv2_0) & tmp_21_reg_3876) & ap_const_lv2_0) & tmp_22_reg_3883) & ap_const_lv2_0) & tmp_23_reg_3890) & ap_const_lv2_0) & tmp_24_reg_3897) & ap_const_lv2_0) & tmp_25_reg_3905) & ap_const_lv2_0) & tmp_26_reg_3913) & ap_const_lv2_0) & tmp_27_reg_3921) & ap_const_lv2_0) & tmp_28_reg_3929) & ap_const_lv2_0) & tmp_29_reg_3937) & ap_const_lv2_0) & tmp_30_reg_3945) & ap_const_lv2_0) & tmp_31_reg_3953) & ap_const_lv2_0) & tmp_32_reg_3961);
    and_ln1497_s_fu_1957_p32 <= ((((((((((((((((((((((((((((((tmp_17_reg_3852 & ap_const_lv2_0) & tmp_18_reg_3857) & ap_const_lv2_0) & tmp_19_reg_3863) & ap_const_lv2_0) & tmp_20_reg_3869) & ap_const_lv2_0) & tmp_21_reg_3876) & ap_const_lv2_0) & tmp_22_reg_3883) & ap_const_lv2_0) & tmp_23_reg_3890) & ap_const_lv2_0) & tmp_24_reg_3897) & ap_const_lv2_0) & tmp_25_reg_3905) & ap_const_lv2_0) & tmp_26_reg_3913) & ap_const_lv2_0) & tmp_27_reg_3921) & ap_const_lv2_0) & tmp_28_reg_3929) & ap_const_lv2_0) & tmp_29_reg_3937) & ap_const_lv2_0) & tmp_30_reg_3945) & ap_const_lv2_0) & tmp_31_reg_3953) & ap_const_lv2_0) & tmp_32_reg_3961);
    and_ln1669_2_fu_3302_p15 <= (((((((((((((ap_const_lv1_0 & tmp_99_fu_3238_p4) & ap_const_lv4_0) & tmp_100_fu_3248_p4) & ap_const_lv4_0) & tmp_101_fu_3258_p4) & ap_const_lv4_0) & tmp_102_fu_3268_p4) & ap_const_lv4_0) & tmp_103_fu_3278_p4) & ap_const_lv4_0) & tmp_104_fu_3288_p4) & ap_const_lv4_0) & trunc_ln1669_6_fu_3298_p1);
    and_ln1_fu_2394_p15 <= (((((((((((((ap_const_lv1_0 & tmp_33_fu_2330_p4) & ap_const_lv4_0) & tmp_34_fu_2340_p4) & ap_const_lv4_0) & tmp_35_fu_2350_p4) & ap_const_lv4_0) & tmp_36_fu_2360_p4) & ap_const_lv4_0) & tmp_37_fu_2370_p4) & ap_const_lv4_0) & tmp_38_fu_2380_p4) & ap_const_lv4_0) & trunc_ln1669_fu_2390_p1);
    and_ln2_fu_2590_p11 <= (((((((((ap_const_lv1_0 & tmp_46_fu_2546_p4) & ap_const_lv4_0) & tmp_47_fu_2556_p4) & ap_const_lv4_0) & tmp_48_fu_2566_p4) & ap_const_lv4_0) & tmp_49_fu_2576_p4) & ap_const_lv4_0) & trunc_ln840_fu_2586_p1);
    and_ln840_1_fu_3498_p11 <= (((((((((ap_const_lv1_0 & tmp_113_fu_3454_p4) & ap_const_lv4_0) & tmp_114_fu_3464_p4) & ap_const_lv4_0) & tmp_115_fu_3474_p4) & ap_const_lv4_0) & tmp_116_fu_3484_p4) & ap_const_lv4_0) & trunc_ln840_6_fu_3494_p1);
    and_ln_fu_681_p64 <= ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((tmp_fu_425_p3 & ap_const_lv1_0) & tmp_54_fu_433_p3) & ap_const_lv1_0) & tmp_55_fu_441_p3) & ap_const_lv1_0) & tmp_56_fu_449_p3) & ap_const_lv1_0) & tmp_57_fu_457_p3) & ap_const_lv1_0) & tmp_58_fu_465_p3) & ap_const_lv1_0) & tmp_59_fu_473_p3) & ap_const_lv1_0) & tmp_60_fu_481_p3) & ap_const_lv1_0) & tmp_61_fu_489_p3) & ap_const_lv1_0) & tmp_62_fu_497_p3) & ap_const_lv1_0) & tmp_63_fu_505_p3) & ap_const_lv1_0) & tmp_64_fu_513_p3) & ap_const_lv1_0) & tmp_65_fu_521_p3) & ap_const_lv1_0) & tmp_66_fu_529_p3) & ap_const_lv1_0) & tmp_67_fu_537_p3) & ap_const_lv1_0) & tmp_68_fu_545_p3) & ap_const_lv1_0) & tmp_69_fu_553_p3) & ap_const_lv1_0) & tmp_70_fu_561_p3) & ap_const_lv1_0) & tmp_86_fu_569_p3) & ap_const_lv1_0) & tmp_109_fu_577_p3) & ap_const_lv1_0) & tmp_121_fu_585_p3) & ap_const_lv1_0) & tmp_122_fu_593_p3) & ap_const_lv1_0) & tmp_123_fu_601_p3) & ap_const_lv1_0) & tmp_124_fu_609_p3) & ap_const_lv1_0) & tmp_125_fu_617_p3) & ap_const_lv1_0) & tmp_126_fu_625_p3) & ap_const_lv1_0) & tmp_127_fu_633_p3) & ap_const_lv1_0) & tmp_128_fu_641_p3) & ap_const_lv1_0) & tmp_129_fu_649_p3) & ap_const_lv1_0) & tmp_130_fu_657_p3) & ap_const_lv1_0) & tmp_131_fu_665_p3) & ap_const_lv1_0) & tmp_132_fu_673_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1027_fu_330_p2)
    begin
        if (((icmp_ln1027_fu_330_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_V_8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, rhs_V_fu_238)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_V_8 <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_i_V_8 <= rhs_V_fu_238;
        end if; 
    end process;

    conv_i749_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_s_fu_346_p4),64));
    dmem_V_address0 <= zext_ln624_1_fu_387_p1(12 - 1 downto 0);
    dmem_V_address1 <= zext_ln624_fu_376_p1(12 - 1 downto 0);

    dmem_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dmem_V_ce0 <= ap_const_logic_1;
        else 
            dmem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dmem_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dmem_V_ce1 <= ap_const_logic_1;
        else 
            dmem_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    i_V_fu_408_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_V_8) + unsigned(ap_const_lv16_80));
    icmp_ln1027_fu_330_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_V_8) < unsigned(n_inputs)) else "0";
    or_ln624_fu_381_p2 <= (tmp_1_fu_366_p4 or ap_const_lv12_400);
    ret_V_fu_340_p2 <= std_logic_vector(unsigned(phi_mul) + unsigned(zext_ln1495_fu_336_p1));
    ret_V_s_fu_346_p4 <= ret_V_fu_340_p2(19 downto 7);
        sext_ln624_fu_2758_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln638_fu_2752_p2),10));

        sext_ln840_7_fu_3676_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln840_26_fu_3670_p2),16));

        sext_ln840_fu_3666_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln638_1_fu_3660_p2),10));

    shl_ln1669_1_fu_3648_p3 <= (add_ln1669_3_fu_3642_p2 & ap_const_lv1_0);
    shl_ln_fu_2740_p3 <= (add_ln1669_1_fu_2734_p2 & ap_const_lv1_0);
    sub_ln638_1_fu_3660_p2 <= std_logic_vector(unsigned(ap_const_lv9_40) - unsigned(zext_ln638_1_fu_3656_p1));
    sub_ln638_fu_2752_p2 <= std_logic_vector(unsigned(ap_const_lv9_40) - unsigned(zext_ln638_fu_2748_p1));
    sub_ln841_1_fu_1531_p2 <= std_logic_vector(unsigned(xor_ln1499_1_fu_1135_p2) - unsigned(zext_ln841_1_fu_1527_p1));
    sub_ln841_fu_815_p2 <= std_logic_vector(unsigned(xor_ln1499_fu_419_p2) - unsigned(zext_ln841_fu_811_p1));
    sum_V_out <= sum_V_fu_234;

    sum_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln1027_reg_3710)
    begin
        if (((icmp_ln1027_reg_3710 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sum_V_out_ap_vld <= ap_const_logic_1;
        else 
            sum_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_100_fu_3248_p4 <= add_ln632_7_fu_3226_p2(43 downto 40);
    tmp_101_fu_3258_p4 <= add_ln632_7_fu_3226_p2(35 downto 32);
    tmp_102_fu_3268_p4 <= add_ln632_7_fu_3226_p2(27 downto 24);
    tmp_103_fu_3278_p4 <= add_ln632_7_fu_3226_p2(19 downto 16);
    tmp_104_fu_3288_p4 <= add_ln632_7_fu_3226_p2(11 downto 8);
    tmp_105_fu_3338_p4 <= add_ln632_1_fu_3194_p2(59 downto 56);
    tmp_106_fu_3348_p4 <= add_ln632_1_fu_3194_p2(51 downto 48);
    tmp_107_fu_3358_p4 <= add_ln632_1_fu_3194_p2(43 downto 40);
    tmp_108_fu_3368_p4 <= add_ln632_1_fu_3194_p2(35 downto 32);
    tmp_109_fu_577_p3 <= xor_ln1499_fu_419_p2(25 downto 25);
    tmp_110_fu_3378_p4 <= add_ln632_1_fu_3194_p2(27 downto 24);
    tmp_111_fu_3388_p4 <= add_ln632_1_fu_3194_p2(19 downto 16);
    tmp_112_fu_3398_p4 <= add_ln632_1_fu_3194_p2(11 downto 8);
    tmp_113_fu_3454_p4 <= add_ln1669_8_fu_3232_p2(35 downto 32);
    tmp_114_fu_3464_p4 <= add_ln1669_8_fu_3232_p2(27 downto 24);
    tmp_115_fu_3474_p4 <= add_ln1669_8_fu_3232_p2(19 downto 16);
    tmp_116_fu_3484_p4 <= add_ln1669_8_fu_3232_p2(11 downto 8);
    tmp_121_fu_585_p3 <= xor_ln1499_fu_419_p2(23 downto 23);
    tmp_122_fu_593_p3 <= xor_ln1499_fu_419_p2(21 downto 21);
    tmp_123_fu_601_p3 <= xor_ln1499_fu_419_p2(19 downto 19);
    tmp_124_fu_609_p3 <= xor_ln1499_fu_419_p2(17 downto 17);
    tmp_125_fu_617_p3 <= xor_ln1499_fu_419_p2(15 downto 15);
    tmp_126_fu_625_p3 <= xor_ln1499_fu_419_p2(13 downto 13);
    tmp_127_fu_633_p3 <= xor_ln1499_fu_419_p2(11 downto 11);
    tmp_128_fu_641_p3 <= xor_ln1499_fu_419_p2(9 downto 9);
    tmp_129_fu_649_p3 <= xor_ln1499_fu_419_p2(7 downto 7);
    tmp_130_fu_657_p3 <= xor_ln1499_fu_419_p2(5 downto 5);
    tmp_131_fu_665_p3 <= xor_ln1499_fu_419_p2(3 downto 3);
    tmp_132_fu_673_p3 <= xor_ln1499_fu_419_p2(1 downto 1);
    tmp_133_fu_2662_p4 <= add_ln840_20_fu_2646_p2(53 downto 16);
    tmp_134_fu_1141_p3 <= xor_ln1499_1_fu_1135_p2(63 downto 63);
    tmp_135_fu_1149_p3 <= xor_ln1499_1_fu_1135_p2(61 downto 61);
    tmp_136_fu_1157_p3 <= xor_ln1499_1_fu_1135_p2(59 downto 59);
    tmp_137_fu_1165_p3 <= xor_ln1499_1_fu_1135_p2(57 downto 57);
    tmp_138_fu_1173_p3 <= xor_ln1499_1_fu_1135_p2(55 downto 55);
    tmp_139_fu_1181_p3 <= xor_ln1499_1_fu_1135_p2(53 downto 53);
    tmp_140_fu_1189_p3 <= xor_ln1499_1_fu_1135_p2(51 downto 51);
    tmp_141_fu_1197_p3 <= xor_ln1499_1_fu_1135_p2(49 downto 49);
    tmp_142_fu_1205_p3 <= xor_ln1499_1_fu_1135_p2(47 downto 47);
    tmp_143_fu_1213_p3 <= xor_ln1499_1_fu_1135_p2(45 downto 45);
    tmp_144_fu_1221_p3 <= xor_ln1499_1_fu_1135_p2(43 downto 43);
    tmp_145_fu_1229_p3 <= xor_ln1499_1_fu_1135_p2(41 downto 41);
    tmp_146_fu_1237_p3 <= xor_ln1499_1_fu_1135_p2(39 downto 39);
    tmp_147_fu_1245_p3 <= xor_ln1499_1_fu_1135_p2(37 downto 37);
    tmp_148_fu_1253_p3 <= xor_ln1499_1_fu_1135_p2(35 downto 35);
    tmp_149_fu_1261_p3 <= xor_ln1499_1_fu_1135_p2(33 downto 33);
    tmp_150_fu_1269_p3 <= xor_ln1499_1_fu_1135_p2(31 downto 31);
    tmp_151_fu_1277_p3 <= xor_ln1499_1_fu_1135_p2(29 downto 29);
    tmp_152_fu_1285_p3 <= xor_ln1499_1_fu_1135_p2(27 downto 27);
    tmp_153_fu_1293_p3 <= xor_ln1499_1_fu_1135_p2(25 downto 25);
    tmp_169_fu_1301_p3 <= xor_ln1499_1_fu_1135_p2(23 downto 23);
    tmp_192_fu_1309_p3 <= xor_ln1499_1_fu_1135_p2(21 downto 21);
    tmp_1_fu_366_p4 <= ((d_i_idx & ap_const_lv2_0) & tmp_s_fu_356_p4);
    tmp_204_fu_1317_p3 <= xor_ln1499_1_fu_1135_p2(19 downto 19);
    tmp_205_fu_1325_p3 <= xor_ln1499_1_fu_1135_p2(17 downto 17);
    tmp_206_fu_1333_p3 <= xor_ln1499_1_fu_1135_p2(15 downto 15);
    tmp_207_fu_1341_p3 <= xor_ln1499_1_fu_1135_p2(13 downto 13);
    tmp_208_fu_1349_p3 <= xor_ln1499_1_fu_1135_p2(11 downto 11);
    tmp_209_fu_1357_p3 <= xor_ln1499_1_fu_1135_p2(9 downto 9);
    tmp_210_fu_1365_p3 <= xor_ln1499_1_fu_1135_p2(7 downto 7);
    tmp_211_fu_1373_p3 <= xor_ln1499_1_fu_1135_p2(5 downto 5);
    tmp_212_fu_1381_p3 <= xor_ln1499_1_fu_1135_p2(3 downto 3);
    tmp_213_fu_1389_p3 <= xor_ln1499_1_fu_1135_p2(1 downto 1);
    tmp_214_fu_3570_p4 <= add_ln840_24_fu_3554_p2(53 downto 16);
    tmp_33_fu_2330_p4 <= add_ln632_4_fu_2318_p2(51 downto 48);
    tmp_34_fu_2340_p4 <= add_ln632_4_fu_2318_p2(43 downto 40);
    tmp_35_fu_2350_p4 <= add_ln632_4_fu_2318_p2(35 downto 32);
    tmp_36_fu_2360_p4 <= add_ln632_4_fu_2318_p2(27 downto 24);
    tmp_37_fu_2370_p4 <= add_ln632_4_fu_2318_p2(19 downto 16);
    tmp_38_fu_2380_p4 <= add_ln632_4_fu_2318_p2(11 downto 8);
    tmp_39_fu_2430_p4 <= add_ln632_fu_2286_p2(59 downto 56);
    tmp_40_fu_2440_p4 <= add_ln632_fu_2286_p2(51 downto 48);
    tmp_41_fu_2450_p4 <= add_ln632_fu_2286_p2(43 downto 40);
    tmp_42_fu_2460_p4 <= add_ln632_fu_2286_p2(35 downto 32);
    tmp_43_fu_2470_p4 <= add_ln632_fu_2286_p2(27 downto 24);
    tmp_44_fu_2480_p4 <= add_ln632_fu_2286_p2(19 downto 16);
    tmp_45_fu_2490_p4 <= add_ln632_fu_2286_p2(11 downto 8);
    tmp_46_fu_2546_p4 <= add_ln1669_2_fu_2324_p2(35 downto 32);
    tmp_47_fu_2556_p4 <= add_ln1669_2_fu_2324_p2(27 downto 24);
    tmp_48_fu_2566_p4 <= add_ln1669_2_fu_2324_p2(19 downto 16);
    tmp_49_fu_2576_p4 <= add_ln1669_2_fu_2324_p2(11 downto 8);
    tmp_54_fu_433_p3 <= xor_ln1499_fu_419_p2(61 downto 61);
    tmp_55_fu_441_p3 <= xor_ln1499_fu_419_p2(59 downto 59);
    tmp_56_fu_449_p3 <= xor_ln1499_fu_419_p2(57 downto 57);
    tmp_57_fu_457_p3 <= xor_ln1499_fu_419_p2(55 downto 55);
    tmp_58_fu_465_p3 <= xor_ln1499_fu_419_p2(53 downto 53);
    tmp_59_fu_473_p3 <= xor_ln1499_fu_419_p2(51 downto 51);
    tmp_60_fu_481_p3 <= xor_ln1499_fu_419_p2(49 downto 49);
    tmp_61_fu_489_p3 <= xor_ln1499_fu_419_p2(47 downto 47);
    tmp_62_fu_497_p3 <= xor_ln1499_fu_419_p2(45 downto 45);
    tmp_63_fu_505_p3 <= xor_ln1499_fu_419_p2(43 downto 43);
    tmp_64_fu_513_p3 <= xor_ln1499_fu_419_p2(41 downto 41);
    tmp_65_fu_521_p3 <= xor_ln1499_fu_419_p2(39 downto 39);
    tmp_66_fu_529_p3 <= xor_ln1499_fu_419_p2(37 downto 37);
    tmp_67_fu_537_p3 <= xor_ln1499_fu_419_p2(35 downto 35);
    tmp_68_fu_545_p3 <= xor_ln1499_fu_419_p2(33 downto 33);
    tmp_69_fu_553_p3 <= xor_ln1499_fu_419_p2(31 downto 31);
    tmp_70_fu_561_p3 <= xor_ln1499_fu_419_p2(29 downto 29);
    tmp_86_fu_569_p3 <= xor_ln1499_fu_419_p2(27 downto 27);
    tmp_99_fu_3238_p4 <= add_ln632_7_fu_3226_p2(51 downto 48);
    tmp_fu_425_p3 <= xor_ln1499_fu_419_p2(63 downto 63);
    tmp_s_fu_356_p4 <= ap_sig_allocacmp_i_V_8(15 downto 7);
    trunc_ln1497_1_fu_1687_p1 <= sub_ln841_1_fu_1531_p2(2 - 1 downto 0);
    trunc_ln1497_fu_971_p1 <= sub_ln841_fu_815_p2(2 - 1 downto 0);
    trunc_ln1669_1_fu_3616_p4 <= add_ln840_25_fu_3600_p2(38 downto 32);
    trunc_ln1669_2_fu_2080_p27 <= (((((((((((((((((((((((((ap_const_lv1_0 & tmp_5_reg_3751) & ap_const_lv2_0) & tmp_6_reg_3758) & ap_const_lv2_0) & tmp_7_reg_3765) & ap_const_lv2_0) & tmp_8_reg_3772) & ap_const_lv2_0) & tmp_9_reg_3779) & ap_const_lv2_0) & tmp_10_reg_3787) & ap_const_lv2_0) & tmp_11_reg_3795) & ap_const_lv2_0) & tmp_12_reg_3803) & ap_const_lv2_0) & tmp_13_reg_3811) & ap_const_lv2_0) & tmp_14_reg_3819) & ap_const_lv2_0) & tmp_15_reg_3827) & ap_const_lv2_0) & tmp_16_reg_3835) & ap_const_lv2_0) & trunc_ln1497_reg_3843);
    trunc_ln1669_3_fu_2127_p27 <= (((((((((((((((((((((((((ap_const_lv1_0 & tmp_20_reg_3869) & ap_const_lv2_0) & tmp_21_reg_3876) & ap_const_lv2_0) & tmp_22_reg_3883) & ap_const_lv2_0) & tmp_23_reg_3890) & ap_const_lv2_0) & tmp_24_reg_3897) & ap_const_lv2_0) & tmp_25_reg_3905) & ap_const_lv2_0) & tmp_26_reg_3913) & ap_const_lv2_0) & tmp_27_reg_3921) & ap_const_lv2_0) & tmp_28_reg_3929) & ap_const_lv2_0) & tmp_29_reg_3937) & ap_const_lv2_0) & tmp_30_reg_3945) & ap_const_lv2_0) & tmp_31_reg_3953) & ap_const_lv2_0) & tmp_32_reg_3961);
    trunc_ln1669_4_fu_2988_p27 <= (((((((((((((((((((((((((ap_const_lv1_0 & tmp_53_reg_3987) & ap_const_lv2_0) & tmp_71_reg_3994) & ap_const_lv2_0) & tmp_72_reg_4001) & ap_const_lv2_0) & tmp_73_reg_4008) & ap_const_lv2_0) & tmp_74_reg_4015) & ap_const_lv2_0) & tmp_75_reg_4023) & ap_const_lv2_0) & tmp_76_reg_4031) & ap_const_lv2_0) & tmp_77_reg_4039) & ap_const_lv2_0) & tmp_78_reg_4047) & ap_const_lv2_0) & tmp_79_reg_4055) & ap_const_lv2_0) & tmp_80_reg_4063) & ap_const_lv2_0) & tmp_81_reg_4071) & ap_const_lv2_0) & trunc_ln1497_1_reg_4079);
    trunc_ln1669_5_fu_3035_p27 <= (((((((((((((((((((((((((ap_const_lv1_0 & tmp_85_reg_4105) & ap_const_lv2_0) & tmp_87_reg_4112) & ap_const_lv2_0) & tmp_88_reg_4119) & ap_const_lv2_0) & tmp_89_reg_4126) & ap_const_lv2_0) & tmp_90_reg_4133) & ap_const_lv2_0) & tmp_91_reg_4141) & ap_const_lv2_0) & tmp_92_reg_4149) & ap_const_lv2_0) & tmp_93_reg_4157) & ap_const_lv2_0) & tmp_94_reg_4165) & ap_const_lv2_0) & tmp_95_reg_4173) & ap_const_lv2_0) & tmp_96_reg_4181) & ap_const_lv2_0) & tmp_97_reg_4189) & ap_const_lv2_0) & tmp_98_reg_4197);
    trunc_ln1669_6_fu_3298_p1 <= add_ln632_7_fu_3226_p2(4 - 1 downto 0);
    trunc_ln1669_fu_2390_p1 <= add_ln632_4_fu_2318_p2(4 - 1 downto 0);
    trunc_ln1_fu_2680_p3 <= (ap_const_lv1_0 & tmp_45_fu_2490_p4);
    trunc_ln2_fu_2708_p4 <= add_ln840_21_fu_2692_p2(38 downto 32);
    trunc_ln632_10_cast_fu_3216_p4 <= add_ln631_3_fu_2976_p2(39 downto 4);
    trunc_ln632_1_fu_3200_p4 <= add_ln631_3_fu_2976_p2(7 downto 4);
    trunc_ln632_2_fu_2180_p4 <= add_ln631_fu_2074_p2(62 downto 4);
    trunc_ln632_3_fu_2200_p19 <= (((((((((((((((((ap_const_lv1_0 & tmp_9_reg_3779) & ap_const_lv2_0) & tmp_10_reg_3787) & ap_const_lv2_0) & tmp_11_reg_3795) & ap_const_lv2_0) & tmp_12_reg_3803) & ap_const_lv2_0) & tmp_13_reg_3811) & ap_const_lv2_0) & tmp_14_reg_3819) & ap_const_lv2_0) & tmp_15_reg_3827) & ap_const_lv2_0) & tmp_16_reg_3835) & ap_const_lv2_0) & trunc_ln1497_reg_3843);
    trunc_ln632_4_fu_2235_p19 <= (((((((((((((((((ap_const_lv1_0 & tmp_24_reg_3897) & ap_const_lv2_0) & tmp_25_reg_3905) & ap_const_lv2_0) & tmp_26_reg_3913) & ap_const_lv2_0) & tmp_27_reg_3921) & ap_const_lv2_0) & tmp_28_reg_3929) & ap_const_lv2_0) & tmp_29_reg_3937) & ap_const_lv2_0) & tmp_30_reg_3945) & ap_const_lv2_0) & tmp_31_reg_3953) & ap_const_lv2_0) & tmp_32_reg_3961);
    trunc_ln632_5_cast_fu_2276_p4 <= add_ln631_2_fu_2068_p2(55 downto 4);
    trunc_ln632_6_cast_fu_2308_p4 <= add_ln631_2_fu_2068_p2(39 downto 4);
    trunc_ln632_7_fu_3088_p4 <= add_ln631_1_fu_2982_p2(62 downto 4);
    trunc_ln632_8_fu_3108_p19 <= (((((((((((((((((ap_const_lv1_0 & tmp_74_reg_4015) & ap_const_lv2_0) & tmp_75_reg_4023) & ap_const_lv2_0) & tmp_76_reg_4031) & ap_const_lv2_0) & tmp_77_reg_4039) & ap_const_lv2_0) & tmp_78_reg_4047) & ap_const_lv2_0) & tmp_79_reg_4055) & ap_const_lv2_0) & tmp_80_reg_4063) & ap_const_lv2_0) & tmp_81_reg_4071) & ap_const_lv2_0) & trunc_ln1497_1_reg_4079);
    trunc_ln632_9_fu_3143_p19 <= (((((((((((((((((ap_const_lv1_0 & tmp_90_reg_4133) & ap_const_lv2_0) & tmp_91_reg_4141) & ap_const_lv2_0) & tmp_92_reg_4149) & ap_const_lv2_0) & tmp_93_reg_4157) & ap_const_lv2_0) & tmp_94_reg_4165) & ap_const_lv2_0) & tmp_95_reg_4173) & ap_const_lv2_0) & tmp_96_reg_4181) & ap_const_lv2_0) & tmp_97_reg_4189) & ap_const_lv2_0) & tmp_98_reg_4197);
    trunc_ln632_cast_fu_3184_p4 <= add_ln631_3_fu_2976_p2(55 downto 4);
    trunc_ln840_1_fu_2698_p4 <= add_ln840_20_fu_2646_p2(22 downto 16);
    trunc_ln840_2_fu_3588_p3 <= (ap_const_lv1_0 & tmp_112_fu_3398_p4);
    trunc_ln840_3_fu_3606_p4 <= add_ln840_24_fu_3554_p2(22 downto 16);
    trunc_ln840_4_fu_2500_p14 <= ((((((((((((tmp_39_fu_2430_p4 & ap_const_lv4_0) & tmp_40_fu_2440_p4) & ap_const_lv4_0) & tmp_41_fu_2450_p4) & ap_const_lv4_0) & tmp_42_fu_2460_p4) & ap_const_lv4_0) & tmp_43_fu_2470_p4) & ap_const_lv4_0) & tmp_44_fu_2480_p4) & ap_const_lv4_0) & tmp_45_fu_2490_p4);
    trunc_ln840_5_fu_2618_p11 <= (((((((((ap_const_lv1_0 & tmp_41_fu_2450_p4) & ap_const_lv4_0) & tmp_42_fu_2460_p4) & ap_const_lv4_0) & tmp_43_fu_2470_p4) & ap_const_lv4_0) & tmp_44_fu_2480_p4) & ap_const_lv4_0) & tmp_45_fu_2490_p4);
    trunc_ln840_6_fu_3494_p1 <= add_ln1669_8_fu_3232_p2(4 - 1 downto 0);
    trunc_ln840_7_fu_3408_p14 <= ((((((((((((tmp_105_fu_3338_p4 & ap_const_lv4_0) & tmp_106_fu_3348_p4) & ap_const_lv4_0) & tmp_107_fu_3358_p4) & ap_const_lv4_0) & tmp_108_fu_3368_p4) & ap_const_lv4_0) & tmp_110_fu_3378_p4) & ap_const_lv4_0) & tmp_111_fu_3388_p4) & ap_const_lv4_0) & tmp_112_fu_3398_p4);
    trunc_ln840_8_fu_3526_p11 <= (((((((((ap_const_lv1_0 & tmp_107_fu_3358_p4) & ap_const_lv4_0) & tmp_108_fu_3368_p4) & ap_const_lv4_0) & tmp_110_fu_3378_p4) & ap_const_lv4_0) & tmp_111_fu_3388_p4) & ap_const_lv4_0) & tmp_112_fu_3398_p4);
    trunc_ln840_fu_2586_p1 <= add_ln1669_2_fu_2324_p2(4 - 1 downto 0);
    trunc_ln_fu_2292_p4 <= add_ln631_2_fu_2068_p2(7 downto 4);
    wt_mem_V_address0 <= zext_ln625_fu_403_p1(13 - 1 downto 0);
    wt_mem_V_address1 <= conv_i749_fu_392_p1(13 - 1 downto 0);

    wt_mem_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            wt_mem_V_ce0 <= ap_const_logic_1;
        else 
            wt_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    wt_mem_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            wt_mem_V_ce1 <= ap_const_logic_1;
        else 
            wt_mem_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1499_1_fu_1135_p2 <= (wt_mem_V_q0 xor dmem_V_q0);
    xor_ln1499_fu_419_p2 <= (wt_mem_V_q1 xor dmem_V_q1);
    zext_ln1495_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_V_8),20));
    zext_ln1669_1_fu_2861_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_2_fu_2762_p32),63));
    zext_ln1669_2_fu_2123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1669_2_fu_2080_p27),52));
    zext_ln1669_3_fu_2170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1669_3_fu_2127_p27),52));
    zext_ln1669_4_fu_2426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1_fu_2394_p15),54));
    zext_ln1669_5_fu_2724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1669_5_fu_2718_p2),7));
    zext_ln1669_6_fu_3031_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1669_4_fu_2988_p27),52));
    zext_ln1669_7_fu_3078_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1669_5_fu_3035_p27),52));
    zext_ln1669_8_fu_3334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1669_2_fu_3302_p15),54));
    zext_ln1669_9_fu_3632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1669_10_fu_3626_p2),7));
    zext_ln1669_fu_1953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_9_fu_1854_p32),63));
    zext_ln624_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln624_fu_381_p2),64));
    zext_ln624_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_366_p4),64));
    zext_ln625_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln625_fu_397_p2),64));
    zext_ln631_1_fu_2964_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_3_fu_2865_p32),63));
    zext_ln631_2_fu_2060_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_9_cast_fu_1904_p31),60));
    zext_ln631_3_fu_2064_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_cast_fu_2007_p31),60));
    zext_ln631_4_fu_2968_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_2_cast_fu_2812_p31),60));
    zext_ln631_5_fu_2972_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_3_cast_fu_2915_p31),60));
    zext_ln631_fu_2056_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_s_fu_1957_p32),63));
    zext_ln632_1_fu_2194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1497_reg_3843),4));
    zext_ln632_2_fu_2197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_reg_3961),4));
    zext_ln632_3_fu_3098_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_7_fu_3088_p4),60));
    zext_ln632_4_fu_3102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1497_1_reg_4079),4));
    zext_ln632_5_fu_3105_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_98_reg_4197),4));
    zext_ln632_6_fu_2231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_3_fu_2200_p19),36));
    zext_ln632_7_fu_2266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_4_fu_2235_p19),36));
    zext_ln632_8_fu_3139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_8_fu_3108_p19),36));
    zext_ln632_9_fu_3174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_9_fu_3143_p19),36));
    zext_ln632_fu_2190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln632_2_fu_2180_p4),60));
    zext_ln638_1_fu_3656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1669_1_fu_3648_p3),9));
    zext_ln638_fu_2748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_2740_p3),9));
    zext_ln840_10_fu_3566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1669_9_fu_3560_p2),39));
    zext_ln840_11_fu_3580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_214_fu_3570_p4),39));
    zext_ln840_12_fu_3584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_23_fu_3448_p2),6));
    zext_ln840_13_fu_3596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln840_2_fu_3588_p3),6));
    zext_ln840_1_fu_2614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln2_fu_2590_p11),38));
    zext_ln840_2_fu_2642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln840_5_fu_2618_p11),38));
    zext_ln840_3_fu_2658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1669_4_fu_2652_p2),39));
    zext_ln840_4_fu_2672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_133_fu_2662_p4),39));
    zext_ln840_5_fu_2676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_fu_2540_p2),6));
    zext_ln840_6_fu_2688_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_fu_2680_p3),6));
    zext_ln840_7_fu_3438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln840_7_fu_3408_p14),54));
    zext_ln840_8_fu_3522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln840_1_fu_3498_p11),38));
    zext_ln840_9_fu_3550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln840_8_fu_3526_p11),38));
    zext_ln840_fu_2530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln840_4_fu_2500_p14),54));
    zext_ln841_1_fu_1527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1497_1_fu_1397_p64),64));
    zext_ln841_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_681_p64),64));
end behav;
